export type Pin = {
  id: string;
  x: number;
  y: number;
  href: string;
  label: { en: string; el: string };
  tagline: { en: string; el: string };
};

/*
  ── HOW TO ADD A NEW DESTINATION PIN ──
  Coordinates are percentages of the SVG viewBox (0 0 1000 1000).
  Use the browser console (F12) debug mode or calculate from lat/lon:
    svg_x ≈ (102.81*lon - 0.06*lat - 1958.18) / 10
    svg_y ≈ (10.05*lon - 143.53*lat + 5756.30) / 10
*/

export const MAP_PINS: Pin[] = [
  {
    id: "santorini",
    x: 65.7, y: 75.9,
    href: "/destinations/santorini",
    label: { en: "Santorini", el: "Σαντορίνη" },
    tagline: { en: "Iconic caldera views", el: "Εμβληματική θέα Καλντέρας" },
  },
  {
    id: "mykonos",
    x: 64.9, y: 62.1,
    href: "/destinations/mykonos",
    label: { en: "Mykonos", el: "Μύκονος" },
    tagline: { en: "Cosmopolitan island life", el: "Κοσμοπολίτικη νησιωτική ζωή" },
  },
  {
    id: "paros",
    x: 63.0, y: 67.2,
    href: "/destinations/paros",
    label: { en: "Paros", el: "Πάρος" },
    tagline: { en: "Beaches & traditional charm", el: "Παραλίες & παραδοσιακή γοητεία" },
  },
  {
    id: "naxos",
    x: 66.3, y: 67.6,
    href: "/destinations/naxos",
    label: { en: "Naxos", el: "Νάξος" },
    tagline: { en: "Beaches & mountain villages", el: "Παραλίες & ορεινά χωριά" },
  },
  {
    id: "milos",
    x: 55.2, y: 71.9,
    href: "/destinations/milos",
    label: { en: "Milos", el: "Μήλος" },
    tagline: { en: "Unique coastline & caves", el: "Μοναδικές ακτές & σπηλιές" },
  },
  {
    id: "crete",
    x: 60.0, y: 91.0,
    href: "/destinations/crete",
    label: { en: "Crete", el: "Κρήτη" },
    tagline: { en: "A world of its own", el: "Ένας ολόκληρος κόσμος" },
  },
  {
    id: "chania",
    x: 50.9, y: 86.5,
    href: "/destinations/chania",
    label: { en: "Chania", el: "Χανιά" },
    tagline: { en: "Venetian harbor & old town", el: "Ενετικό λιμάνι & παλιά πόλη" },
  },
  {
    id: "rhodes",
    x: 91.1, y: 78.1,
    href: "/destinations/rhodes",
    label: { en: "Rhodes", el: "Ρόδος" },
    tagline: { en: "Medieval old town & beaches", el: "Μεσαιωνική πόλη & παραλίες" },
  },
  {
    id: "patmos",
    x: 76.9, y: 63.8,
    href: "/destinations/patmos",
    label: { en: "Patmos", el: "Πάτμος" },
    tagline: { en: "Sacred island & quiet bays", el: "Ιερό νησί & ήσυχοι όρμοι" },
  },
  {
    id: "corfu",
    x: 8.7, y: 32.8,
    href: "/destinations/corfu",
    label: { en: "Corfu", el: "Κέρκυρα" },
    tagline: { en: "Lush green & elegant", el: "Καταπράσινο & κομψό" },
  },
  {
    id: "kefalonia",
    x: 14.6, y: 51.4,
    href: "/destinations/kefalonia",
    label: { en: "Kefalonia", el: "Κεφαλονιά" },
    tagline: { en: "Dramatic scenery & beaches", el: "Εντυπωσιακά τοπία & παραλίες" },
  },
  {
    id: "zakynthos",
    x: 17.3, y: 57.2,
    href: "/destinations/zakynthos",
    label: { en: "Zakynthos", el: "Ζάκυνθος" },
    tagline: { en: "Iconic shipwreck beach", el: "Εμβληματικό Ναυάγιο" },
  },
  {
    id: "lesvos",
    x: 74.6, y: 39.9,
    href: "/destinations/lesvos",
    label: { en: "Lesvos", el: "Λέσβος" },
    tagline: { en: "Food & tradition", el: "Γαστρονομία & παράδοση" },
  },
  {
    id: "aegina",
    x: 44.8, y: 57.4,
    href: "/destinations/aegina",
    label: { en: "Aegina", el: "Αίγινα" },
    tagline: { en: "Temple of Aphaia & pistachios", el: "Ναός Αφαίας & φιστίκια" },
  },
  {
    id: "hydra",
    x: 45.1, y: 63.1,
    href: "/destinations/hydra",
    label: { en: "Hydra", el: "Ύδρα" },
    tagline: { en: "Car-free island & art scene", el: "Νησί χωρίς αυτοκίνητα & τέχνη" },
  },
  {
    id: "athens",
    x: 47.9, y: 54.4,
    href: "/destinations/athens",
    label: { en: "Athens", el: "Αθήνα" },
    tagline: { en: "Ancient & modern capital", el: "Αρχαία & σύγχρονη πρωτεύουσα" },
  },
  {
    id: "thessaloniki",
    x: 39.8, y: 18.9,
    href: "/destinations/thessaloniki",
    label: { en: "Thessaloniki", el: "Θεσσαλονίκη" },
    tagline: { en: "Food & culture hub", el: "Κέντρο γαστρονομίας & πολιτισμού" },
  },
  {
    id: "halkidiki",
    x: 45.0, y: 27.8,
    href: "/destinations/halkidiki",
    label: { en: "Halkidiki", el: "Χαλκιδική" },
    tagline: { en: "Turquoise waters & pine", el: "Γαλαζοπράσινα νερά & πεύκα" },
  },
  {
    id: "nafplio",
    x: 38.4, y: 59.3,
    href: "/destinations/nafplio",
    label: { en: "Nafplio", el: "Ναύπλιο" },
    tagline: { en: "Romantic seaside town", el: "Ρομαντική παραθαλάσσια πόλη" },
  },
  {
    id: "monemvasia",
    x: 40.9, y: 72.2,
    href: "/destinations/monemvasia",
    label: { en: "Monemvasia", el: "Μονεμβασία" },
    tagline: { en: "Medieval fortress town", el: "Μεσαιωνική καστροπολιτεία" },
  },
  {
    id: "parga",
    x: 13.5, y: 37.3,
    href: "/destinations/parga",
    label: { en: "Parga", el: "Πάργα" },
    tagline: { en: "Colorful coastal gem", el: "Πολύχρωμο παραθαλάσσιο στολίδι" },
  },
  {
    id: "meteora",
    x: 27.3, y: 31.3,
    href: "/destinations/meteora",
    label: { en: "Meteora", el: "Μετέωρα" },
    tagline: { en: "Monasteries in the sky", el: "Μοναστήρια στον ουρανό" },
  },
  {
    id: "delphi",
    x: 35.3, y: 47.9,
    href: "/destinations/delphi",
    label: { en: "Delphi", el: "Δελφοί" },
    tagline: { en: "Center of the ancient world", el: "Κέντρο του αρχαίου κόσμου" },
  },
  {
    id: "patras",
    x: 27.3, y: 51.5,
    href: "/destinations/patras",
    label: { en: "Patras", el: "Πάτρα" },
    tagline: { en: "Gateway to the Ionian", el: "Πύλη προς το Ιόνιο" },
  },
  {
    id: "kalamata",
    x: 31.3, y: 66.2,
    href: "/destinations/kalamata",
    label: { en: "Kalamata", el: "Καλαμάτα" },
    tagline: { en: "Peloponnese coastal city", el: "Παραθαλάσσια πόλη Πελοποννήσου" },
  },
  {
    id: "skiathos",
    x: 45.4, y: 39.2,
    href: "/destinations/skiathos",
    label: { en: "Skiathos", el: "Σκιάθος" },
    tagline: { en: "Pine forests & turquoise waters", el: "Πεύκα & τιρκουάζ νερά" },
  },
  {
    id: "skopelos",
    x: 47.9, y: 40.0,
    href: "/destinations/skopelos",
    label: { en: "Skopelos", el: "Σκόπελος" },
    tagline: { en: "The greenest island", el: "Το πιο πράσινο νησί" },
  },
  {
    id: "thassos",
    x: 58.0, y: 19.0,
    href: "/destinations/thassos",
    label: { en: "Thassos", el: "Θάσος" },
    tagline: { en: "Greece's greenest island", el: "Το πιο πράσινο νησί της Ελλάδας" },
  },
  {
    id: "lemnos",
    x: 62.6, y: 29.4,
    href: "/destinations/lemnos",
    label: { en: "Lemnos", el: "Λήμνος" },
    tagline: { en: "Aegean island escape", el: "Αιγαιοπελαγίτικη απόδραση" },
  },
  {
    id: "ikaria",
    x: 72.9, y: 60.2,
    href: "/destinations/ikaria",
    label: { en: "Ikaria", el: "Ικαρία" },
    tagline: { en: "The Blue Zone island", el: "Το νησί της μακροζωίας" },
  },
  {
    id: "evia",
    x: 49.1, y: 47.0,
    href: "/destinations/evia",
    label: { en: "Evia", el: "Εύβοια" },
    tagline: { en: "Wild nature & thermal springs", el: "Άγρια φύση & ιαματικές πηγές" },
  },
  {
    id: "lefkada",
    x: 15.9, y: 45.1,
    href: "/destinations/lefkada",
    label: { en: "Lefkada", el: "Λευκάδα" },
    tagline: { en: "Turquoise beaches & drive access", el: "Τιρκουάζ παραλίες & οδική πρόσβαση" },
  },
  {
    id: "preveza",
    x: 17.3, y: 41.4,
    href: "/destinations/preveza",
    label: { en: "Preveza", el: "Πρέβεζα" },
    tagline: { en: "Undersea tunnel beaches & ancient Nicopolis", el: "Παραλίες, υποθαλάσσια σήραγγα & αρχαία Νικόπολη" },
  },
  {
    id: "kos",
    x: 82.5, y: 70.7,
    href: "/destinations/kos",
    label: { en: "Kos", el: "Κως" },
    tagline: { en: "History, beaches & cycling", el: "Ιστορία, παραλίες & ποδήλατο" },
  },
  {
    id: "rethymno",
    x: 55.5, y: 88.1,
    href: "/destinations/rethymno",
    label: { en: "Rethymno", el: "Ρέθυμνο" },
    tagline: { en: "Venetian old town & Fortezza", el: "Ενετική πόλη & Φορτέτζα" },
  },
  {
    id: "heraklion",
    x: 62.4, y: 89.2,
    href: "/destinations/heraklion",
    label: { en: "Heraklion", el: "Ηράκλειο" },
    tagline: { en: "Knossos, market & Venetian harbour", el: "Κνωσός, αγορά & ενετικό λιμάνι" },
  },
  {
    id: "lasithi",
    x: 68.4, y: 90.9,
    href: "/destinations/lasithi",
    label: { en: "Lasithi", el: "Λασίθι" },
    tagline: { en: "Spinalonga & eastern Crete", el: "Σπιναλόγκα & ανατολική Κρήτη" },
  },
  {
    id: "syros",
    x: 60.4, y: 63.2,
    href: "/destinations/syros",
    label: { en: "Syros", el: "Σύρος" },
    tagline: { en: "Capital of the Cyclades", el: "Πρωτεύουσα των Κυκλάδων" },
  },
  {
    id: "tinos",
    x: 62.6, y: 59.5,
    href: "/destinations/tinos",
    label: { en: "Tinos", el: "Τήνος" },
    tagline: { en: "Sacred island & marble capital", el: "Ιερό νησί & πρωτεύουσα μαρμάρου" },
  },
  {
    id: "ios",
    x: 64.4, y: 72.0,
    href: "/destinations/ios",
    label: { en: "Ios", el: "Ίος" },
    tagline: { en: "Wild beaches, Homer's Tomb & nightlife", el: "Άγριες παραλίες, Τάφος Ομήρου & νυχτερινή ζωή" },
  },
  {
    id: "andros",
    x: 59.3, y: 56.7,
    href: "/destinations/andros",
    label: { en: "Andros", el: "Άνδρος" },
    tagline: { en: "Hiking capital of the Cyclades", el: "Πρωτεύουσα πεζοπορίας των Κυκλάδων" },
  },
  {
    id: "nafpaktos",
    x: 28.3, y: 50.0,
    href: "/destinations/nafpaktos",
    label: { en: "Nafpaktos", el: "Ναύπακτος" },
    tagline: { en: "Lepanto's Venetian harbour", el: "Το βενετσιάνικο λιμάνι της Ναυπάκτου" },
  },
  {
    id: "karpathos",
    x: 83.7, y: 86.3,
    href: "/destinations/karpathos",
    label: { en: "Karpathos", el: "Κάρπαθος" },
    tagline: { en: "Island of the Winds", el: "Νησί των Ανέμων" },
  },
  {
    id: "kea",
    x: 54.0, y: 60.0,
    href: "/destinations/kea",
    label: { en: "Kea", el: "Κέα" },
    tagline: { en: "Lion, Ioulida & Britannic shipwreck", el: "Λιοντάρι, Ιουλίδα & Britannic" },
  },
  {
    id: "chios",
    x: 71.7, y: 50.2,
    href: "/destinations/chios",
    label: { en: "Chios", el: "Χίος" },
    tagline: { en: "Mastica villages & medieval castles", el: "Μαστιχοχώρια & μεσαιωνικά κάστρα" },
  },
  {
    id: "samos",
    x: 80.2, y: 58.8,
    href: "/destinations/samos",
    label: { en: "Samos", el: "Σάμος" },
    tagline: { en: "Pythagoras, wine & beaches", el: "Πυθαγόρας, κρασί & παραλίες" },
  },
  {
    id: "kalymnos",
    x: 81.4, y: 68.1,
    href: "/destinations/kalymnos",
    label: { en: "Kalymnos", el: "Κάλυμνος" },
    tagline: { en: "World capital of rock climbing", el: "Παγκόσμια πρωτεύουσα αναρρίχησης" },
  },
  {
    id: "samothraki",
    x: 67.3, y: 22.5,
    href: "/destinations/samothraki",
    label: { en: "Samothraki", el: "Σαμοθράκη" },
    tagline: { en: "Sanctuary of the Great Gods", el: "Ιερό των Μεγάλων Θεών" },
  },
];
