import type { TourExperience } from "./types";

export const tourExperiences: TourExperience[] = [
  // ═══ SANTORINI ═══
  {
    slug: "santorini-semi-private-catamaran-cruise",
    title: { en: "Santorini Semi-Private Catamaran Cruise with Meal & Open Bar", el: "Ημι-ιδιωτική Κρουαζιέρα με Καταμαράν στη Σαντορίνη" },
    shortDescription: { en: "Sail past the volcanic Red and White beaches, swim in the warm sulfur springs, and enjoy a freshly prepared Greek BBQ meal on board.", el: "Πλεύστε δίπλα από την Κόκκινη και Λευκή παραλία, κολυμπήστε στις θερμές πηγές και απολαύστε φρεσκομαγειρεμένο ελληνικό BBQ." },
    destination: "Santorini",
    region: "Cyclades",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 135,
    priceLabel: { en: "from €135/person", el: "από €135/άτομο" },
    rating: 4.9,
    reviewCount: 3120,
    image: "/images/santorini.webp",
    bookingUrl: "https://www.viator.com/tours/Santorini/Semi-Private-Catamaran-Cruise-with-BBQ-and-Open-Bar/d461-5050SEMI?pid=P00298401&mcid=42383",
    highlights: { en: ["Swim in volcanic warm springs", "Sail close to Red & White beaches", "Fresh seafood and meat BBQ", "Unlimited Greek wine and beer"], el: ["Κολύμπι σε θερμές πηγές", "Ιστιοπλοΐα σε Κόκκινη & Λευκή παραλία", "Φρέσκο BBQ με θαλασσινά", "Απεριόριστο κρασί και μπίρα"] },
    included: { en: ["Hotel pickup and drop-off", "Greek BBQ meal (veggie options)", "Open bar with wine, beer, soft drinks", "Snorkeling equipment"], el: ["Παραλαβή από ξενοδοχείο", "Ελληνικό BBQ (vegetarian επιλογές)", "Open bar με κρασί, μπίρα", "Εξοπλισμός snorkeling"] },
    meetingPoint: { en: "Complimentary hotel pickup", el: "Δωρεάν παραλαβή από ξενοδοχείο" },
    groupSize: "Up to 16 guests",
    difficulty: "easy",
    languages: ["en", "el", "fr"],
    badge: "bestseller",
    featured: true
  },
  {
    slug: "santorini-sunset-wine-tour",
    title: { en: "Santorini Sunset Wine Tour with 5 Wineries & Tastings", el: "Οινογευσία στο Ηλιοβασίλεμα με 5 Οινοποιεία" },
    shortDescription: { en: "Visit 5 family-run wineries carved into volcanic cliffs, taste 12+ local Assyrtiko wines, and watch the sunset over the caldera.", el: "Επισκεφθείτε 5 οικογενειακά οινοποιεία, δοκιμάστε 12+ τοπικά κρασιά και απολαύστε το ηλιοβασίλεμα στην καλντέρα." },
    destination: "Santorini",
    region: "Cyclades",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία & Οινογνωσία" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 89,
    priceLabel: { en: "from €89/person", el: "από €89/άτομο" },
    rating: 4.8,
    reviewCount: 1240,
    image: "/images/santorini.webp",
    bookingUrl: "https://www.viator.com/tours/Santorini/Santorini-Sunset-Wine-Tour-with-Dinner/d461-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Visit 5 volcanic wineries", "Taste 12+ Assyrtiko wines", "Sunset over the caldera", "Local cheese pairings"], el: ["Επίσκεψη σε 5 οινοποιεία", "Δοκιμή 12+ κρασιών", "Ηλιοβασίλεμα στην καλντέρα", "Συνοδεία τοπικών τυριών"] },
    included: { en: ["All wine tasting fees", "Expert sommelier guide", "Hotel transfers", "Cheese & cold cuts platter"], el: ["Όλες οι γευσιγνωσίες", "Έμπειρος sommelier", "Μεταφορές από ξενοδοχείο", "Πιατέλα με τυριά"] },
    meetingPoint: { en: "Hotel pickup in Fira or Oia", el: "Παραλαβή από ξενοδοχείο σε Φηρά ή Οία" },
    groupSize: "Up to 12 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "santorini-volcano-hiking-tour",
    title: { en: "Santorini Volcano & Hot Springs Hiking Tour", el: "Πεζοπορία στο Ηφαίστειο & Θερμές Πηγές" },
    shortDescription: { en: "Hike to the crater of the active Nea Kameni volcano, then sail to the hot springs for a therapeutic mud bath and swim.", el: "Πεζοπορήστε στον κρατήρα του ενεργού ηφαιστείου, κολυμπήστε στις θερμές πηγές και απολαύστε θεραπευτική λάσπη." },
    destination: "Santorini",
    region: "Cyclades",
    type: "adventure",
    typeLabel: { en: "Adventure & Hiking", el: "Περιπέτεια & Πεζοπορία" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 45,
    priceLabel: { en: "from €45/person", el: "από €45/άτομο" },
    rating: 4.6,
    reviewCount: 2450,
    image: "/images/santorini.webp",
    bookingUrl: "https://www.viator.com/tours/Santorini/Volcano-and-Hot-Springs-Tour/d461-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Hike the volcano crater", "Mud bath in hot springs", "Spectacular caldera views", "Boat ride across the caldera"], el: ["Πεζοπορία στον κρατήρα", "Μπάνιο λάσπης στις πηγές", "Θέα στην καλντέρα", "Βαρκάδα"] },
    included: { en: ["Ferry tickets to Nea Kameni", "Licensed hiking guide", "Entrance fee to volcano", "Life jackets"], el: ["Εισιτήρια για Νέα Καμένη", "Πιστοποιημένος οδηγός", "Εισιτήριο ηφαιστείου", "Σωσίβια"] },
    meetingPoint: { en: "Fira Old Port cable car station", el: "Σταθμός τελεφερίκ Παλιού Λιμανιού Φηρών" },
    groupSize: "Up to 25 guests",
    difficulty: "moderate",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ ATHENS ═══
  {
    slug: "athens-acropolis-guided-walking-tour",
    title: { en: "Acropolis & Parthenon Guided Walking Tour (Skip-the-Line)", el: "Ξενάγηση Ακρόπολης & Παρθενώνα με Skip-the-Line" },
    shortDescription: { en: "Walk through the Cradle of Western Civilization with a licensed archaeologist. Skip the long ticket lines and learn the history of the Parthenon.", el: "Περπατήστε στο λίκνο του δυτικού πολιτισμού με πιστοποιημένο αρχαιολόγο." },
    destination: "Athens",
    region: "Attica",
    type: "history",
    typeLabel: { en: "History & Archaeology", el: "Ιστορία & Αρχαιολογία" },
    duration: "3 hours",
    durationHours: 3,
    priceFrom: 64,
    priceLabel: { en: "from €64/person", el: "από €64/άτομο" },
    rating: 4.8,
    reviewCount: 4850,
    image: "/images/athens.webp",
    bookingUrl: "https://www.viator.com/tours/Athens/Acropolis-Skip-the-Line/d496-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Skip-the-line entry", "Guided tour of Parthenon", "Panoramic views over Athens", "In-depth mythology explanations"], el: ["Είσοδος χωρίς αναμονή", "Ξενάγηση στον Παρθενώνα", "Πανοραμική θέα Αθήνας", "Μυθολογία"] },
    included: { en: ["Licensed archaeologist guide", "Skip-the-line entrance", "Personal audio headset"], el: ["Πιστοποιημένος αρχαιολόγος", "Είσοδος χωρίς ουρά", "Ατομικά ακουστικά"] },
    meetingPoint: { en: "Acropolis Metro Station", el: "Σταθμός Μετρό Ακρόπολη" },
    groupSize: "Up to 20 guests",
    difficulty: "easy",
    languages: ["en", "el", "de"],
    badge: "bestseller",
    featured: true
  },
  {
    slug: "athens-street-food-walk",
    title: { en: "Athens Gourmet Street Food Tour & Market Walk", el: "Γαστρονομική Περιήγηση & Street Food στην Αθήνα" },
    shortDescription: { en: "Eat like an Athenian! Taste souvlaki, loukoumades, local cheeses, and bougatsa while exploring Plaka, Psirri, and the Varvakios market.", el: "Φάτε σαν Αθηναίος! Δοκιμάστε σουβλάκι, λουκουμάδες και τυριά στην Πλάκα και τον Ψυρρή." },
    destination: "Athens",
    region: "Attica",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία" },
    duration: "3.5 hours",
    durationHours: 3.5,
    priceFrom: 49,
    priceLabel: { en: "from €49/person", el: "από €49/άτομο" },
    rating: 4.8,
    reviewCount: 1640,
    image: "/images/athens.webp",
    bookingUrl: "https://www.viator.com/tours/Athens/Athens-Food-Tour/d496-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["8-10 tastings at 6 stops", "Visit Varvakios Central Market", "Explore Plaka & Psirri", "Greek coffee & olive oil tasting"], el: ["8-10 γεύσεις σε 6 στάσεις", "Επίσκεψη Βαρβάκειου Αγοράς", "Πλάκα & Ψυρρή", "Γευσιγνωσία καφέ & ελαιολάδου"] },
    included: { en: ["Local food guide", "All food tastings (full meal)", "Greek coffee or herbal tea", "Local market tour"], el: ["Τοπικός οδηγός γαστρονομίας", "Όλες οι δοκιμές (πλήρες γεύμα)", "Ελληνικός καφές ή τσάι", "Περιήγηση αγοράς"] },
    meetingPoint: { en: "Monastiraki Square", el: "Πλατεία Μοναστηρακίου" },
    groupSize: "Up to 10 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    badge: "local-favorite",
    featured: false
  },
  {
    slug: "athens-cape-sounion-sunset-tour",
    title: { en: "Cape Sounion & Temple of Poseidon Sunset Tour", el: "Ηλιοβασίλεμα στο Σούνιο & Ναός του Ποσειδώνα" },
    shortDescription: { en: "Drive along the scenic Athenian Riviera to Cape Sounion. Explore the Temple of Poseidon perched on the cliffs and watch the sun sink into the Aegean.", el: "Οδηγήστε στην Αθηναϊκή Ριβιέρα, επισκεφθείτε τον Ναό του Ποσειδώνα και απολαύστε το ηλιοβασίλεμα." },
    destination: "Athens",
    region: "Attica",
    type: "day-trip",
    typeLabel: { en: "Half-Day Trip", el: "Ημερήσια Εκδρομή" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 55,
    priceLabel: { en: "from €55/person", el: "από €55/άτομο" },
    rating: 4.7,
    reviewCount: 1980,
    image: "/images/athens.webp",
    bookingUrl: "https://www.viator.com/tours/Athens/Cape-Sounion-Sunset-Tour/d496-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Temple of Poseidon at sunset", "Athenian Riviera coastal drive", "Professional guide", "Free time at the cape"], el: ["Ναός Ποσειδώνα στο ηλιοβασίλεμα", "Διαδρομή Αθηναϊκής Ριβιέρας", "Επαγγελματίας ξεναγός", "Ελεύθερος χρόνος"] },
    included: { en: ["Air-conditioned bus transport", "English-speaking guide", "Entrance fee", "Hotel pickup option"], el: ["Μεταφορά με λεωφορείο", "Αγγλόφωνος ξεναγός", "Εισιτήριο εισόδου", "Παραλαβή από ξενοδοχείο"] },
    meetingPoint: { en: "Syntagma Square, Athens", el: "Πλατεία Συντάγματος" },
    groupSize: "Up to 30 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ CRETE ═══
  {
    slug: "crete-cooking-class-traditional-village",
    title: { en: "Cretan Cooking Class & Olive Oil Tasting in Traditional Village", el: "Μάθημα Κρητικής Μαγειρικής & Γευσιγνωσία Ελαιολάδου" },
    shortDescription: { en: "Harvest fresh organic vegetables from the garden, cook authentic Cretan recipes in a family estate, and sample award-winning olive oil.", el: "Μαζέψτε βιολογικά λαχανικά, μαγειρέψτε κρητικές συνταγές και δοκιμάστε βραβευμένο ελαιόλαδο." },
    destination: "Crete",
    region: "Crete",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία" },
    duration: "4.5 hours",
    durationHours: 4.5,
    priceFrom: 85,
    priceLabel: { en: "from €85/person", el: "από €85/άτομο" },
    rating: 4.9,
    reviewCount: 940,
    image: "/images/crete.webp",
    bookingUrl: "https://www.viator.com/tours/Crete/Cretan-Cooking-Class/d453-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Cook 5 traditional dishes", "Award-winning olive oil tasting", "Multi-course lunch with wine", "Recipe book to take home"], el: ["Μαγειρέψτε 5 πιάτα", "Γευσιγνωσία βραβευμένου ελαιολάδου", "Γεύμα πολλών πιάτων", "Βιβλίο συνταγών"] },
    included: { en: ["All ingredients & tools", "Professional oil tasting", "Full lunch with wine & raki", "Recipe booklet"], el: ["Όλα τα υλικά & εργαλεία", "Επαγγελματική γευσιγνωσία", "Πλήρες γεύμα με κρασί & ρακή", "Βιβλιαράκι συνταγών"] },
    meetingPoint: { en: "Vamos Village, Apokoronas", el: "Χωριό Βάμος, Αποκόρωνας" },
    groupSize: "Up to 12 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    badge: "local-favorite",
    featured: true
  },
  {
    slug: "crete-knossos-archaeological-tour",
    title: { en: "Knossos Palace & Heraklion Archaeological Museum Guided Tour", el: "Ξενάγηση στο Παλάτι της Κνωσού & Μουσείο Ηρακλείου" },
    shortDescription: { en: "Explore the legendary Minoan Palace of Knossos with an archaeologist. See the throne room, frescoes, and the treasures of the Heraklion Museum.", el: "Εξερευνήστε το μινωικό ανάκτορο με αρχαιολόγο. Δείτε τον θρόνο, τις τοιχογραφίες και τους θησαυρούς του Μουσείου." },
    destination: "Crete",
    region: "Crete",
    type: "history",
    typeLabel: { en: "History & Archaeology", el: "Ιστορία" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 60,
    priceLabel: { en: "from €60/person", el: "από €60/άτομο" },
    rating: 4.7,
    reviewCount: 3200,
    image: "/images/crete.webp",
    bookingUrl: "https://www.viator.com/tours/Crete/Knossos-Palace-Tour/d453-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Minoan Palace of Knossos", "Throne Room & frescoes", "Heraklion Museum artifacts", "Skip-the-line entry"], el: ["Μινωικό ανάκτορο Κνωσού", "Θρόνος & τοιχογραφίες", "Εκθέματα Μουσείου Ηρακλείου", "Είσοδος χωρίς ουρά"] },
    included: { en: ["Licensed archaeological guide", "Skip-the-line tickets", "Museum entrance fee", "Audio headsets"], el: ["Πιστοποιημένος αρχαιολόγος", "Εισιτήρια χωρίς ουρά", "Είσοδος μουσείου", "Ακουστικά"] },
    meetingPoint: { en: "Knossos Palace main entrance", el: "Κεντρική είσοδος Κνωσού" },
    groupSize: "Up to 18 guests",
    difficulty: "easy",
    languages: ["en", "el", "fr"],
    badge: "bestseller",
    featured: false
  },
  {
    slug: "crete-samaria-gorge-hiking",
    title: { en: "Samaria Gorge Full Day Hiking Adventure from Chania", el: "Πεζοπορία στο Φαράγγι της Σαμαριάς από τα Χανιά" },
    shortDescription: { en: "Hike through Europe's longest gorge (16 km) in the White Mountains. Swim at the stunning beach of Agia Roumeli and take the ferry back.", el: "Πεζοπορήστε στο μεγαλύτερο φαράγγι της Ευρώπης, κολυμπήστε στην Αγία Ρουμέλη και επιστρέψτε με πλοίο." },
    destination: "Crete",
    region: "Crete",
    type: "adventure",
    typeLabel: { en: "Adventure & Hiking", el: "Περιπέτεια" },
    duration: "10 hours",
    durationHours: 10,
    priceFrom: 35,
    priceLabel: { en: "from €35/person", el: "από €35/άτομο" },
    rating: 4.6,
    reviewCount: 4100,
    image: "/images/crete.webp",
    bookingUrl: "https://www.viator.com/tours/Crete/Samaria-Gorge-Hiking-Tour/d453-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["16 km gorge hike", "White Mountains scenery", "Swim at Agia Roumeli", "Ferry ride across Libyan Sea"], el: ["Πεζοπορία 16 χλμ", "Τοπία Λευκών Ορέων", "Κολύμπι στην Αγία Ρουμέλη", "Διαδρομή με πλοίο"] },
    included: { en: ["Bus transport from Chania", "National park entrance fee", "Licensed hiking guide", "Ferry ticket to Chora Sfakion"], el: ["Μεταφορά από Χανιά", "Εισιτήριο Εθνικού Δρυμού", "Πιστοποιημένος οδηγός", "Εισιτήριο πλοίου"] },
    meetingPoint: { en: "Chania central bus station", el: "Κεντρικός σταθμός λεωφορείων Χανίων" },
    groupSize: "Up to 25 guests",
    difficulty: "challenging",
    languages: ["en", "el", "de"],
    badge: "bestseller",
    featured: false
  },

  // ═══ MYKONOS ═══
  {
    slug: "mykonos-delos-guided-archaeological-tour",
    title: { en: "Delos Island Sacred Archaeological Guided Tour from Mykonos", el: "Ξενάγηση στην Ιερή Δήλο από τη Μύκονο" },
    shortDescription: { en: "Take a 30-minute boat trip to the uninhabited sacred island of Delos, birthplace of Apollo and Artemis, and explore its spectacular ruins.", el: "Κάντε 30' με καΐκι στην ιερή Δήλο και εξερευνήστε τα ερείπια με αρχαιολόγο." },
    destination: "Mykonos",
    region: "Cyclades",
    type: "history",
    typeLabel: { en: "History & Archaeology", el: "Ιστορία" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 65,
    priceLabel: { en: "from €65/person", el: "από €65/άτομο" },
    rating: 4.7,
    reviewCount: 1850,
    image: "/images/mykonos.webp",
    bookingUrl: "https://www.viator.com/tours/Mykonos/Delos-Island-Tour/d479-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Terrace of the Lions", "Ancient theatre ruins", "Archaeological museum", "Scenic boat cruise"], el: ["Οδός Λεόντων", "Αρχαίο θέατρο", "Αρχαιολογικό μουσείο", "Κρουαζιέρα"] },
    included: { en: ["Round-trip boat tickets", "Licensed guide", "Entrance fee to Delos", "Audio headsets"], el: ["Εισιτήρια πλοίου μετ' επιστροφής", "Πιστοποιημένος ξεναγός", "Εισιτήριο Δήλου", "Ακουστικά"] },
    meetingPoint: { en: "Mykonos Old Port", el: "Παλιό Λιμάνι Μυκόνου" },
    groupSize: "Up to 25 guests",
    difficulty: "moderate",
    languages: ["en", "el", "fr"],
    badge: "bestseller",
    featured: true
  },
  {
    slug: "mykonos-catamaran-cruise",
    title: { en: "Mykonos Luxury Catamaran Cruise with BBQ & Open Bar", el: "Πολυτελής Κρουαζιέρα με Καταμαράν στη Μύκονο" },
    shortDescription: { en: "Sail around the southern coast of Mykonos on a luxury catamaran. Stop at Rhenia island for swimming and enjoy a BBQ lunch prepared by the crew.", el: "Πλεύστε γύρω από τη Μύκονο με πολυτελές καταμαράν. Σταματήστε στη Ρήνεια και απολαύστε BBQ." },
    destination: "Mykonos",
    region: "Cyclades",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 120,
    priceLabel: { en: "from €120/person", el: "από €120/άτομο" },
    rating: 4.8,
    reviewCount: 890,
    image: "/images/mykonos.webp",
    bookingUrl: "https://www.viator.com/tours/Mykonos/Catamaran-Cruise/d479-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Luxury catamaran experience", "Swimming at Rhenia island", "BBQ lunch & open bar", "Snorkeling equipment"], el: ["Πολυτελές καταμαράν", "Κολύμπι στη Ρήνεια", "BBQ & open bar", "Εξοπλισμός snorkeling"] },
    included: { en: ["Catamaran cruise", "BBQ lunch", "Open bar with wine, beer, cocktails", "Snorkeling gear", "Hotel pickup"], el: ["Κρουαζιέρα με καταμαράν", "BBQ γεύμα", "Open bar", "Εξοπλισμός snorkeling", "Παραλαβή"] },
    meetingPoint: { en: "Mykonos Old Port Marina", el: "Μαρίνα Παλιού Λιμανιού" },
    groupSize: "Up to 14 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ KEFALONIA ═══
  {
    slug: "kefalonia-melissani-lake-myrtos-beach-day-trip",
    title: { en: "Kefalonia Highlights: Melissani, Drogarati & Myrtos Viewpoint", el: "Τα Highlights της Κεφαλονιάς: Μελισσάνη, Δρογκαράτη & Μύρτος" },
    shortDescription: { en: "Ride a boat inside Melissani underground lake, see ancient stalactites in Drogarati Cave, and take photos at the iconic Myrtos Beach viewpoint.", el: "Βαρκάδα στη λίμνη Μελισσάνης, σταλακτίτες στη Δρογκαράτη και φωτογραφία στον Μύρτο." },
    destination: "Kefalonia",
    region: "Ionian Islands",
    type: "day-trip",
    typeLabel: { en: "Full Day Trip", el: "Ολοήμερη Εκδρομή" },
    duration: "6 hours",
    durationHours: 6,
    priceFrom: 55,
    priceLabel: { en: "from €55/person", el: "από €55/άτομο" },
    rating: 4.8,
    reviewCount: 1220,
    image: "/images/kefalonia.webp",
    bookingUrl: "https://www.viator.com/tours/Kefalonia/Kefalonia-Highlights-Tour/d459-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Melissani cave rowboat ride", "Drogarati stalactite cave", "Myrtos Beach viewpoint", "Agia Efimia village lunch"], el: ["Βαρκάδα στη Μελισσάνη", "Σπήλαιο Δρογκαράτη", "Θέα Μύρτου", "Γεύμα στην Αγία Ευφημία"] },
    included: { en: ["Luxury bus transport", "Local expert guide", "Rowboat in Melissani cave", "Hotel pickup/drop-off"], el: ["Μεταφορά με λεωφορείο", "Τοπικός ξεναγός", "Βαρκάδα στη Μελισσάνη", "Παραλαβή από ξενοδοχείο"] },
    meetingPoint: { en: "Argostoli Port terminal", el: "Λιμάνι Αργοστολίου" },
    groupSize: "Up to 20 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    badge: "local-favorite",
    featured: true
  },
  {
    slug: "kefalonia-boat-cruise-ithaca",
    title: { en: "Kefalonia Full-Day Boat Cruise to Ithaca & Fiskardo", el: "Ολοήμερη Κρουαζιέρα σε Ιθάκη & Φισκάρδο" },
    shortDescription: { en: "Sail across the Ionian Sea to the mythical island of Ithaca. Swim in secluded bays, visit the picturesque village of Fiskardo, and enjoy a fresh seafood lunch.", el: "Πλεύστε στο Ιόνιο προς την Ιθάκη. Κολυμπήστε σε κρυφές παραλίες και απολαύστε φρέσκο ψάρι στο Φισκάρδο." },
    destination: "Kefalonia",
    region: "Ionian Islands",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "8 hours",
    durationHours: 8,
    priceFrom: 95,
    priceLabel: { en: "from €95/person", el: "από €95/άτομο" },
    rating: 4.7,
    reviewCount: 670,
    image: "/images/kefalonia.webp",
    bookingUrl: "https://www.viator.com/tours/Kefalonia/Ithaca-Boat-Cruise/d459-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Sail to Ithaca island", "Swim in secluded bays", "Visit Fiskardo village", "Seafood lunch onboard"], el: ["Ιστιοπλοΐα στην Ιθάκη", "Κολύμπι σε κρυφές παραλίες", "Επίσκεψη Φισκάρδου", "Γεύμα με ψάρι"] },
    included: { en: ["Boat cruise", "Seafood lunch", "Snorkeling equipment", "Beach towels"], el: ["Κρουαζιέρα", "Γεύμα με θαλασσινά", "Εξοπλισμός snorkeling", "Πετσέτες παραλίας"] },
    meetingPoint: { en: "Fiskardo Port", el: "Λιμάνι Φισκάρδου" },
    groupSize: "Up to 30 guests",
    difficulty: "easy",
    languages: ["en", "el", "it"],
    featured: false
  },

  // ═══ METEGRA ═══
  {
    slug: "meteora-sunset-monasteries-tour",
    title: { en: "Meteora Sunset Tour: Monasteries, Hermit Caves & Views", el: "Εκδρομή στο Ηλιοβασίλεμα των Μετεώρων" },
    shortDescription: { en: "Visit cliff-top Byzantine monasteries, explore ancient hermit caves, and watch the sunset paint the rock pillars in golden light.", el: "Επισκεφθείτε μοναστήρια, σπηλιές ασκητών και θαυμάστε το ηλιοβασίλεμα." },
    destination: "Meteora",
    region: "Thessaly",
    type: "nature",
    typeLabel: { en: "Nature & Cultural", el: "Φύση & Πολιτισμός" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 45,
    priceLabel: { en: "from €45/person", el: "από €45/άτομο" },
    rating: 4.9,
    reviewCount: 2210,
    image: "/images/meteora.webp",
    bookingUrl: "https://www.viator.com/tours/Meteora/Meteora-Sunset-Tour/d422-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Sunset from best viewpoints", "Visit 1-2 monasteries", "Hidden hermit caves", "Monk history stories"], el: ["Ηλιοβασίλεμα από καλύτερα σημεία", "Επίσκεψη μοναστηριών", "Ασκητικές σπηλιές", "Ιστορία μοναχών"] },
    included: { en: ["VIP minibus transport", "Local guide", "Free Wi-Fi", "Hotel pickup"], el: ["Μεταφορά με VIP μίνιμπας", "Τοπικός ξεναγός", "Δωρεάν Wi-Fi", "Παραλαβή"] },
    meetingPoint: { en: "Kalampaka train station", el: "Σιδηροδρομικός σταθμός Καλαμπάκας" },
    groupSize: "Up to 15 guests",
    difficulty: "easy",
    languages: ["en", "el", "es"],
    badge: "bestseller",
    featured: true
  },
  {
    slug: "meteora-hiking-adventure",
    title: { en: "Meteora Hiking & Rock Climbing Adventure", el: "Πεζοπορία & Αναρρίχηση στα Μετέωρα" },
    shortDescription: { en: "Explore hidden trails between the giant rock pillars. For the adventurous, try rock climbing on authentic Meteora routes with a professional instructor.", el: "Εξερευνήστε κρυφά μονοπάτια. Για τους τολμηρούς, αναρριχηθείτε σε αυθεντικές διαδρομές." },
    destination: "Meteora",
    region: "Thessaly",
    type: "adventure",
    typeLabel: { en: "Adventure & Hiking", el: "Περιπέτεια" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 70,
    priceLabel: { en: "from €70/person", el: "από €70/άτομο" },
    rating: 4.8,
    reviewCount: 340,
    image: "/images/meteora.webp",
    bookingUrl: "https://www.viator.com/tours/Meteora/Meteora-Hiking-Tour/d422-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Hidden trails between pillars", "Rock climbing routes", "Professional instructor", "Panoramic views"], el: ["Κρυφά μονοπάτια", "Διαδρομές αναρρίχησης", "Επαγγελματίας εκπαιδευτής", "Πανοραμική θέα"] },
    included: { en: ["Experienced hiking guide", "Climbing equipment", "Safety harness & helmet", "Hotel transfer"], el: ["Έμπειρος οδηγός", "Εξοπλισμός αναρρίχησης", "Ζώνη & κράνος", "Μεταφορά"] },
    meetingPoint: { en: "Kastraki Village square", el: "Πλατεία Καστρακίου" },
    groupSize: "Up to 8 guests",
    difficulty: "challenging",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ ZAKYNTHOS ═══
  {
    slug: "zakynthos-navagio-shipwreck-blue-caves",
    title: { en: "Zakynthos: Navagio Shipwreck & Blue Caves Speedboat Tour", el: "Ζάκυνθος: Ναυάγιο & Γαλάζιες Σπηλιές με Ταχύπλοο" },
    shortDescription: { en: "Hop on a speedboat to Zakynthos' most famous landmarks. Swim inside the glowing Blue Caves and walk the white sands of Shipwreck beach.", el: "Επιβιβαστείτε σε ταχύπλοο για το Ναυάγιο και τις Γαλάζιες Σπηλιές." },
    destination: "Zakynthos",
    region: "Ionian Islands",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "4.5 hours",
    durationHours: 4.5,
    priceFrom: 50,
    priceLabel: { en: "from €50/person", el: "από €50/άτομο" },
    rating: 4.6,
    reviewCount: 2150,
    image: "/images/zakynthos.webp",
    bookingUrl: "https://www.viator.com/tours/Zakynthos/Navagio-Beaches-and-Blue-Caves-Cruise/d456-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Swim inside Blue Caves", "Shipwreck beach access", "Speedboat ride", "Turtle spotting in Marathias"], el: ["Γαλάζιες σπηλιές", "Παραλία Ναυαγίου", "Ταχύπλοο", "Χελώνες Caretta-Caretta"] },
    included: { en: ["Speedboat with skipper", "Snorkeling masks", "Hotel pickup", "Beach time at Navagio"], el: ["Ταχύπλοο με καπετάνιο", "Μάσκες snorkeling", "Παραλαβή", "Χρόνος στο Ναυάγιο"] },
    meetingPoint: { en: "Porto Vromi port or hotel pickup", el: "Λιμάνι Πόρτο Βρώμη" },
    groupSize: "Up to 20 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    badge: "bestseller",
    featured: false
  },

  // ═══ RHODES ═══
  {
    slug: "rhodes-medieval-town-private-walking-tour",
    title: { en: "Rhodes Medieval City Private Walking Tour with Licensed Guide", el: "Ιδιωτική Ξενάγηση στη Μεσαιωνική Πόλη της Ρόδου" },
    shortDescription: { en: "Step inside the largest active medieval city in Europe. Walk the Street of the Knights, visit the Palace of the Grand Master, and discover hidden Byzantine corners.", el: "Περπατήστε στην Οδό των Ιπποτών και το Παλάτι του Μεγάλου Μαγίστρου." },
    destination: "Rhodes",
    region: "Dodecanese",
    type: "cultural",
    typeLabel: { en: "Cultural & Walking", el: "Πολιτισμός" },
    duration: "3 hours",
    durationHours: 3,
    priceFrom: 120,
    priceLabel: { en: "from €120/group", el: "από €120/γκρουπ" },
    rating: 4.9,
    reviewCount: 340,
    image: "/images/rhodes.webp",
    bookingUrl: "https://www.viator.com/tours/Rhodes/Private-Walking-Tour-Medieval-City/d463-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Private tour", "Palace of the Grand Master", "Street of the Knights", "Byzantine & Ottoman history"], el: ["Ιδιωτική ξενάγηση", "Παλάτι Μεγάλου Μαγίστρου", "Οδός Ιπποτών", "Βυζαντινή ιστορία"] },
    included: { en: ["Licensed guide for your party", "Skip-the-line palace tickets", "Tailored recommendations"], el: ["Πιστοποιημένος ξεναγός", "Εισιτήρια χωρίς ουρά", "Προτάσεις διαμονής"] },
    meetingPoint: { en: "Marine Gate, Medieval Town", el: "Θαλασσινή Πύλη, Παλιά Πόλη" },
    groupSize: "Private (Up to 8)",
    difficulty: "easy",
    languages: ["en", "el", "de", "fr"],
    badge: "exclusive",
    featured: false
  },
  {
    slug: "rhodes-lindos-acropolis-tour",
    title: { en: "Lindos Acropolis & Traditional Village Tour", el: "Ξενάγηση στην Ακρόπολη της Λίνδου" },
    shortDescription: { en: "Climb to the ancient Acropolis of Lindos with panoramic views of St. Paul's Bay. Explore the whitewashed village streets and charming squares.", el: "Ανεβείτε στην αρχαία Ακρόπολη της Λίνδου και εξερευνήστε το γραφικό χωριό." },
    destination: "Rhodes",
    region: "Dodecanese",
    type: "history",
    typeLabel: { en: "History & Archaeology", el: "Ιστορία" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 50,
    priceLabel: { en: "from €50/person", el: "από €50/άτομο" },
    rating: 4.6,
    reviewCount: 1780,
    image: "/images/rhodes.webp",
    bookingUrl: "https://www.viator.com/tours/Rhodes/Lindos-Acropolis-Tour/d463-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Lindos Acropolis views", "St. Paul's Bay panorama", "Traditional village walk", "Ancient Greek & medieval history"], el: ["Ακρόπολη Λίνδου", "Όρμος Αγίου Παύλου", "Παραδοσιακό χωριό", "Αρχαία & μεσαιωνική ιστορία"] },
    included: { en: ["Bus transport from Rhodes Town", "Licensed guide", "Entrance fee", "Free time in Lindos village"], el: ["Λεωφορείο από Ρόδο", "Πιστοποιημένος ξεναγός", "Εισιτήριο", "Ελεύθερος χρόνος"] },
    meetingPoint: { en: "Eleftherias Square, Rhodes Town", el: "Πλατεία Ελευθερίας, Πόλη Ρόδου" },
    groupSize: "Up to 20 guests",
    difficulty: "moderate",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ CORFU ═══
  {
    slug: "corfu-old-town-walking-food-tour",
    title: { en: "Corfu Old Town Walking Food Tour with Tastings", el: "Γαστρονομική Περιήγηση στην Παλιά Πόλη της Κέρκυρας" },
    shortDescription: { en: "Explore Corfu's Venetian Old Town through its flavors: taste pastitsada, kumquat liqueur, local wines, and traditional olive oil.", el: "Γνωρίστε την Κέρκυρα μέσα από τις γεύσεις της. Δοκιμάστε παστιτσάδα, κουμ κουάτ και τοπικό κρασί." },
    destination: "Corfu",
    region: "Ionian Islands",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία" },
    duration: "3 hours",
    durationHours: 3,
    priceFrom: 55,
    priceLabel: { en: "from €55/person", el: "από €55/άτομο" },
    rating: 4.7,
    reviewCount: 920,
    image: "/images/corfu.webp",
    bookingUrl: "https://www.viator.com/tours/Corfu/Corfu-Food-Tour/d452-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["10+ tastings", "Venetian Old Town", "Kumquat liqueur tasting", "Local wine & cheese"], el: ["10+ γεύσεις", "Ενετική Παλιά Πόλη", "Γεύση κουμ κουάτ", "Τοπικό κρασί & τυρί"] },
    included: { en: ["Food guide", "All tastings (full meal)", "Kumquat distillery visit", "Wine tasting"], el: ["Οδηγός γαστρονομίας", "Όλες οι δοκιμές", "Επίσκεψη αποστακτηρίου", "Οινογνωσία"] },
    meetingPoint: { en: "Liston Arcade, Corfu Town", el: "Λιστόν, Κέρκυρα" },
    groupSize: "Up to 10 guests",
    difficulty: "easy",
    languages: ["en", "el", "it"],
    featured: false
  },
  {
    slug: "corfu-paxos-antipaxos-boat-trip",
    title: { en: "Corfu Day Trip: Paxos & Antipaxos Blue Caves Boat Cruise", el: "Ημερήσια Κρουαζιέρα σε Παξούς & Αντίπαξους" },
    shortDescription: { en: "Cruise to the turquoise waters of Paxos and Antipaxos. Swim in the famous Blue Caves and explore the charming harbour village of Gaios.", el: "Κρουαζιέρα στα τιρκουάζ νερά των Παξών. Κολυμπήστε στις Γαλάζιες Σπηλιές." },
    destination: "Corfu",
    region: "Ionian Islands",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "9 hours",
    durationHours: 9,
    priceFrom: 80,
    priceLabel: { en: "from €80/person", el: "από €80/άτομο" },
    rating: 4.5,
    reviewCount: 1450,
    image: "/images/corfu.webp",
    bookingUrl: "https://www.viator.com/tours/Corfu/Paxos-Antipaxos-Day-Cruise/d452-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Blue Caves swimming", "Paxos & Antipaxos", "Gaios village visit", "Lunch on board"], el: ["Γαλάζιες Σπηλιές", "Παξοί & Αντίπαξοι", "Γάιος", "Γεύμα στο πλοίο"] },
    included: { en: ["Boat cruise", "Swimming stops", "Lunch", "Beach time"], el: ["Κρουαζιέρα", "Στάσεις για μπάνιο", "Γεύμα", "Χρόνος σε παραλία"] },
    meetingPoint: { en: "Corfu New Port", el: "Νέο Λιμάνι Κέρκυρας" },
    groupSize: "Up to 40 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ THESSALONIKI ═══
  {
    slug: "thessaloniki-food-walking-tour",
    title: { en: "Thessaloniki Food Tour: The Culinary Capital of Greece", el: "Γαστρονομική Περιήγηση στη Θεσσαλονίκη" },
    shortDescription: { en: "Sample bougatsa, souvlaki, and the best street food of Thessaloniki. Explore the Modiano Market, Ano Poli, and waterfront tavernas.", el: "Δοκιμάστε μπουγάτσα, σουβλάκι και street food στην αγορά Μοδιάνο." },
    destination: "Thessaloniki",
    region: "Macedonia",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία" },
    duration: "3.5 hours",
    durationHours: 3.5,
    priceFrom: 45,
    priceLabel: { en: "from €45/person", el: "από €45/άτομο" },
    rating: 4.7,
    reviewCount: 860,
    image: "/images/thessaloniki.webp",
    bookingUrl: "https://www.viator.com/tours/Thessaloniki/Food-Tour/d489-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Modiano Market", "Bougatsa & souvlaki tasting", "Ano Poli (Upper Town)", "Waterfront tavernas"], el: ["Αγορά Μοδιάνο", "Μπουγάτσα & σουβλάκι", "Άνω Πόλη", "Παραλιακές ταβέρνες"] },
    included: { en: ["Local food guide", "8+ food tastings", "Wine/beer pairing", "Modiano Market tour"], el: ["Τοπικός οδηγός", "8+ γεύσεις", "Συνοδεία κρασιού/μπίρας", "Περιήγηση Μοδιάνο"] },
    meetingPoint: { en: "Aristotelous Square", el: "Πλατεία Αριστοτέλους" },
    groupSize: "Up to 10 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ HALKIDIKI ═══
  {
    slug: "halkidiki-mount-athos-cruise",
    title: { en: "Halkidiki: Mount Athos & Ammouliani Island Cruise", el: "Κρουαζιέρα στο Άγιο Όρος & Αμμουλιανή" },
    shortDescription: { en: "Cruise along the breathtaking coast of Mount Athos, see the Byzantine monasteries from the sea, and swim at Ammouliani island.", el: "Κρουαζιέρα στο Άγιο Όρος με θέα στις μονές και κολύμπι στην Αμμουλιανή." },
    destination: "Halkidiki",
    region: "Macedonia",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "7 hours",
    durationHours: 7,
    priceFrom: 65,
    priceLabel: { en: "from €65/person", el: "από €65/άτομο" },
    rating: 4.6,
    reviewCount: 780,
    image: "/images/halkidiki.webp",
    bookingUrl: "https://www.viator.com/tours/Halkidiki/Mount-Athos-Cruise/d24103-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Mount Athos monasteries", "Ammouliani swimming", "Blue Lagoon stop", "Lunch on board"], el: ["Μονές Αγίου Όρους", "Κολύμπι Αμμουλιανή", "Μπλε Λιμνοθάλασσα", "Γεύμα"] },
    included: { en: ["Boat cruise", "Lunch", "Hotel pickup", "English guide"], el: ["Κρουαζιέρα", "Γεύμα", "Παραλαβή", "Αγγλόφωνος ξεναγός"] },
    meetingPoint: { en: "Ouranoupolis port", el: "Λιμάνι Ουρανούπολης" },
    groupSize: "Up to 50 guests",
    difficulty: "easy",
    languages: ["en", "el", "ru"],
    featured: false
  },

  // ═══ PAROS ═══
  {
    slug: "paros-antiparos-sailing-tour",
    title: { en: "Paros to Antiparos Sailing Catamaran Day Trip", el: "Ιστιοπλοϊκή Εκδρομή από Πάρο προς Αντίπαρο" },
    shortDescription: { en: "Sail across the crystal-clear strait to Antiparos. Swim in turquoise coves, explore the Venetian castle, and enjoy freshly caught seafood.", el: "Πλεύστε προς τον Αντίπαρο, κολυμπήστε σε τιρκουάζ όρμους και δοκιμάστε φρέσκο ψάρι." },
    destination: "Paros",
    region: "Cyclades",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "6 hours",
    durationHours: 6,
    priceFrom: 95,
    priceLabel: { en: "from €95/person", el: "από €95/άτομο" },
    rating: 4.8,
    reviewCount: 560,
    image: "/images/paros.webp",
    bookingUrl: "https://www.viator.com/tours/Paros/Antiparos-Catamaran/d478-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Catamaran sailing", "Antiparos Venetian Castle", "Snorkeling in coves", "Seafood BBQ lunch"], el: ["Ιστιοπλοΐα", "Ενετικό Κάστρο Αντιπάρου", "Snorkeling", "BBQ με θαλασσινά"] },
    included: { en: ["Catamaran cruise", "BBQ lunch", "Open bar", "Snorkeling gear"], el: ["Κρουαζιέρα", "BBQ γεύμα", "Open bar", "Εξοπλισμός snorkeling"] },
    meetingPoint: { en: "Parikia Port, Paros", el: "Λιμάνι Παροικιάς" },
    groupSize: "Up to 12 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "paros-walking-tour-naoussa",
    title: { en: "Paros Walking Tour: Naoussa Harbor & Traditional Villages", el: "Πεζοπορική Περιήγηση στη Νάουσα & τα Χωριά της Πάρου" },
    shortDescription: { en: "Explore the whitewashed streets of Naoussa, Lefkes village, and the Byzantine walking trail with panoramic views.", el: "Εξερευνήστε τα γραφικά σοκάκια της Νάουσας και το παλιό μονοπάτι των Λευκών." },
    destination: "Paros",
    region: "Cyclades",
    type: "cultural",
    typeLabel: { en: "Cultural & Walking", el: "Πολιτισμός" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 40,
    priceLabel: { en: "from €40/person", el: "από €40/άτομο" },
    rating: 4.5,
    reviewCount: 420,
    image: "/images/paros.webp",
    bookingUrl: "https://www.viator.com/tours/Paros/Naoussa-Walking-Tour/d478-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Naoussa fishing harbor", "Lefkes marble village", "Byzantine trail", "Panoramic viewpoints"], el: ["Ψαράδικο λιμάνι Νάουσας", "Λεύκες", "Βυζαντινό μονοπάτι", "Πανοραμική θέα"] },
    included: { en: ["Local walking guide", "Refreshments", "Hotel transfer from Parikia"], el: ["Τοπικός οδηγός", "Αναψυκτικά", "Μεταφορά από Παροικιά"] },
    meetingPoint: { en: "Naoussa central square", el: "Κεντρική πλατεία Νάουσας" },
    groupSize: "Up to 10 guests",
    difficulty: "moderate",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ MILOS ═══
  {
    slug: "milos-kleftiko-sailing-boat-tour",
    title: { en: "Milos Full Day Sailing to Kleftiko Caves & Sykia with BBQ", el: "Ολοήμερη Ιστιοπλοΐα στο Κλέφτικο & τη Συκιά" },
    shortDescription: { en: "Sail around Milos' volcanic coastline. Swim through Kleftiko's crystal pirate caves, explore Sykia Cave, and enjoy a BBQ on board.", el: "Κολυμπήστε στα κρυστάλλινα νερά του Κλέφτικου και απολαύστε BBQ." },
    destination: "Milos",
    region: "Cyclades",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "8 hours",
    durationHours: 8,
    priceFrom: 110,
    priceLabel: { en: "from €110/person", el: "από €110/άτομο" },
    rating: 4.9,
    reviewCount: 780,
    image: "/images/milos.webp",
    bookingUrl: "https://www.viator.com/tours/Milos/Kleftiko-Sailing-Tour/d439-XXX?pid=P00298401&mcid=42383",
    highlights: { en: ["Kleftiko pirate caves", "Sykia Cave swim", "Volcanic coastline", "BBQ cooked on board"], el: ["Κλέφτικο", "Σπήλαιο Συκιάς", "Ηφαιστειακή ακτογραμμή", "BBQ στο σκάφος"] },
    included: { en: ["Skipper & crew", "BBQ lunch & open bar", "GoPro underwater photos", "Snorkeling gear"], el: ["Καπετάνιος & πλήρωμα", "BBQ & open bar", "Υποβρύχιες φωτογραφίες", "Εξοπλισμός snorkeling"] },
    meetingPoint: { en: "Adamantas Marina, Milos", el: "Μαρίνα Αδάμαντα, Μήλος" },
    groupSize: "Up to 10 guests",
    difficulty: "moderate",
    languages: ["en", "el", "it"],
    badge: "new",
    featured: false
  }
];
