import type { TourExperience } from "./types";

export const tourExperiences: TourExperience[] = [
  // ═══ SANTORINI ═══
  {
    slug: "santorini-semi-private-catamaran-cruise",
    title: { en: "Santorini Semi-Private Catamaran Cruise with Meal & Open Bar", el: "Ημι-ιδιωτική Κρουαζιέρα με Καταμαράν στη Σαντορίνη" },
    shortDescription: { en: "Sail past the volcanic Red and White beaches, swim in the warm sulfur springs, and enjoy a freshly prepared Greek BBQ meal on board.", el: "Πλεύστε δίπλα από την Κόκκινη και Λευκή παραλία, κολυμπήστε στις θερμές πηγές και απολαύστε φρεσκομαγειρεμένο ελληνικό BBQ." },
    destination: "Santorini",
    region: "Cyclades",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 135,
    priceLabel: { en: "from €135/person", el: "από €135/άτομο" },
    rating: 4.9,
    reviewCount: 3120,
    image: "/images/santorini.webp",
    bookingUrl: "https://www.viator.com/tours/Santorini/Semi-Private-Catamaran-Cruise-with-BBQ-and-Open-Bar/d461-5050SEMI?pid=P00298401&mcid=42383",
    highlights: { en: ["Swim in volcanic warm springs", "Sail close to Red & White beaches", "Fresh seafood and meat BBQ", "Unlimited Greek wine and beer"], el: ["Κολύμπι σε θερμές πηγές", "Ιστιοπλοΐα σε Κόκκινη & Λευκή παραλία", "Φρέσκο BBQ με θαλασσινά", "Απεριόριστο κρασί και μπίρα"] },
    included: { en: ["Hotel pickup and drop-off", "Greek BBQ meal (veggie options)", "Open bar with wine, beer, soft drinks", "Snorkeling equipment"], el: ["Παραλαβή από ξενοδοχείο", "Ελληνικό BBQ (vegetarian επιλογές)", "Open bar με κρασί, μπίρα", "Εξοπλισμός snorkeling"] },
    meetingPoint: { en: "Complimentary hotel pickup", el: "Δωρεάν παραλαβή από ξενοδοχείο" },
    groupSize: "Up to 16 guests",
    difficulty: "easy",
    languages: ["en", "el", "fr"],
    badge: "bestseller",
    featured: true
  },
  {
    slug: "santorini-sunset-wine-tour",
    title: { en: "Santorini Sunset Wine Tour with 5 Wineries & Tastings", el: "Οινογευσία στο Ηλιοβασίλεμα με 5 Οινοποιεία" },
    shortDescription: { en: "Visit 5 family-run wineries carved into volcanic cliffs, taste 12+ local Assyrtiko wines, and watch the sunset over the caldera.", el: "Επισκεφθείτε 5 οικογενειακά οινοποιεία, δοκιμάστε 12+ τοπικά κρασιά και απολαύστε το ηλιοβασίλεμα στην καλντέρα." },
    destination: "Santorini",
    region: "Cyclades",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία & Οινογνωσία" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 89,
    priceLabel: { en: "from €89/person", el: "από €89/άτομο" },
    rating: 4.8,
    reviewCount: 1240,
    image: "/images/santorini.webp",
    highlights: { en: ["Visit 5 volcanic wineries", "Taste 12+ Assyrtiko wines", "Sunset over the caldera", "Local cheese pairings"], el: ["Επίσκεψη σε 5 οινοποιεία", "Δοκιμή 12+ κρασιών", "Ηλιοβασίλεμα στην καλντέρα", "Συνοδεία τοπικών τυριών"] },
    included: { en: ["All wine tasting fees", "Expert sommelier guide", "Hotel transfers", "Cheese & cold cuts platter"], el: ["Όλες οι γευσιγνωσίες", "Έμπειρος sommelier", "Μεταφορές από ξενοδοχείο", "Πιατέλα με τυριά"] },
    meetingPoint: { en: "Hotel pickup in Fira or Oia", el: "Παραλαβή από ξενοδοχείο σε Φηρά ή Οία" },
    groupSize: "Up to 12 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "santorini-volcano-hiking-tour",
    title: { en: "Santorini Volcano & Hot Springs Hiking Tour", el: "Πεζοπορία στο Ηφαίστειο & Θερμές Πηγές" },
    shortDescription: { en: "Hike to the crater of the active Nea Kameni volcano, then sail to the hot springs for a therapeutic mud bath and swim.", el: "Πεζοπορήστε στον κρατήρα του ενεργού ηφαιστείου, κολυμπήστε στις θερμές πηγές και απολαύστε θεραπευτική λάσπη." },
    destination: "Santorini",
    region: "Cyclades",
    type: "adventure",
    typeLabel: { en: "Adventure & Hiking", el: "Περιπέτεια & Πεζοπορία" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 45,
    priceLabel: { en: "from €45/person", el: "από €45/άτομο" },
    rating: 4.6,
    reviewCount: 2450,
    image: "/images/santorini.webp",
    highlights: { en: ["Hike the volcano crater", "Mud bath in hot springs", "Spectacular caldera views", "Boat ride across the caldera"], el: ["Πεζοπορία στον κρατήρα", "Μπάνιο λάσπης στις πηγές", "Θέα στην καλντέρα", "Βαρκάδα"] },
    included: { en: ["Ferry tickets to Nea Kameni", "Licensed hiking guide", "Entrance fee to volcano", "Life jackets"], el: ["Εισιτήρια για Νέα Καμένη", "Πιστοποιημένος οδηγός", "Εισιτήριο ηφαιστείου", "Σωσίβια"] },
    meetingPoint: { en: "Fira Old Port cable car station", el: "Σταθμός τελεφερίκ Παλιού Λιμανιού Φηρών" },
    groupSize: "Up to 25 guests",
    difficulty: "moderate",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ ATHENS ═══
  {
    slug: "athens-acropolis-guided-walking-tour",
    title: { en: "Acropolis & Parthenon Guided Walking Tour (Skip-the-Line)", el: "Ξενάγηση Ακρόπολης & Παρθενώνα με Skip-the-Line" },
    shortDescription: { en: "Walk through the Cradle of Western Civilization with a licensed archaeologist. Skip the long ticket lines and learn the history of the Parthenon.", el: "Περπατήστε στο λίκνο του δυτικού πολιτισμού με πιστοποιημένο αρχαιολόγο." },
    destination: "Athens",
    region: "Attica",
    type: "history",
    typeLabel: { en: "History & Archaeology", el: "Ιστορία & Αρχαιολογία" },
    duration: "3 hours",
    durationHours: 3,
    priceFrom: 64,
    priceLabel: { en: "from €64/person", el: "από €64/άτομο" },
    rating: 4.8,
    reviewCount: 4850,
    image: "/images/athens.webp",
    highlights: { en: ["Skip-the-line entry", "Guided tour of Parthenon", "Panoramic views over Athens", "In-depth mythology explanations"], el: ["Είσοδος χωρίς αναμονή", "Ξενάγηση στον Παρθενώνα", "Πανοραμική θέα Αθήνας", "Μυθολογία"] },
    included: { en: ["Licensed archaeologist guide", "Skip-the-line entrance", "Personal audio headset"], el: ["Πιστοποιημένος αρχαιολόγος", "Είσοδος χωρίς ουρά", "Ατομικά ακουστικά"] },
    meetingPoint: { en: "Acropolis Metro Station", el: "Σταθμός Μετρό Ακρόπολη" },
    groupSize: "Up to 20 guests",
    difficulty: "easy",
    languages: ["en", "el", "de"],
    badge: "bestseller",
    featured: true
  },
  {
    slug: "athens-street-food-walk",
    title: { en: "Athens Gourmet Street Food Tour & Market Walk", el: "Γαστρονομική Περιήγηση & Street Food στην Αθήνα" },
    shortDescription: { en: "Eat like an Athenian! Taste souvlaki, loukoumades, local cheeses, and bougatsa while exploring Plaka, Psirri, and the Varvakios market.", el: "Φάτε σαν Αθηναίος! Δοκιμάστε σουβλάκι, λουκουμάδες και τυριά στην Πλάκα και τον Ψυρρή." },
    destination: "Athens",
    region: "Attica",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία" },
    duration: "3.5 hours",
    durationHours: 3.5,
    priceFrom: 49,
    priceLabel: { en: "from €49/person", el: "από €49/άτομο" },
    rating: 4.8,
    reviewCount: 1640,
    image: "/images/athens.webp",
    highlights: { en: ["8-10 tastings at 6 stops", "Visit Varvakios Central Market", "Explore Plaka & Psirri", "Greek coffee & olive oil tasting"], el: ["8-10 γεύσεις σε 6 στάσεις", "Επίσκεψη Βαρβάκειου Αγοράς", "Πλάκα & Ψυρρή", "Γευσιγνωσία καφέ & ελαιολάδου"] },
    included: { en: ["Local food guide", "All food tastings (full meal)", "Greek coffee or herbal tea", "Local market tour"], el: ["Τοπικός οδηγός γαστρονομίας", "Όλες οι δοκιμές (πλήρες γεύμα)", "Ελληνικός καφές ή τσάι", "Περιήγηση αγοράς"] },
    meetingPoint: { en: "Monastiraki Square", el: "Πλατεία Μοναστηρακίου" },
    groupSize: "Up to 10 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    badge: "local-favorite",
    featured: false
  },
  {
    slug: "athens-cape-sounion-sunset-tour",
    title: { en: "Cape Sounion & Temple of Poseidon Sunset Tour", el: "Ηλιοβασίλεμα στο Σούνιο & Ναός του Ποσειδώνα" },
    shortDescription: { en: "Drive along the scenic Athenian Riviera to Cape Sounion. Explore the Temple of Poseidon perched on the cliffs and watch the sun sink into the Aegean.", el: "Οδηγήστε στην Αθηναϊκή Ριβιέρα, επισκεφθείτε τον Ναό του Ποσειδώνα και απολαύστε το ηλιοβασίλεμα." },
    destination: "Athens",
    region: "Attica",
    type: "day-trip",
    typeLabel: { en: "Half-Day Trip", el: "Ημερήσια Εκδρομή" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 55,
    priceLabel: { en: "from €55/person", el: "από €55/άτομο" },
    rating: 4.7,
    reviewCount: 1980,
    image: "/images/athens.webp",
    highlights: { en: ["Temple of Poseidon at sunset", "Athenian Riviera coastal drive", "Professional guide", "Free time at the cape"], el: ["Ναός Ποσειδώνα στο ηλιοβασίλεμα", "Διαδρομή Αθηναϊκής Ριβιέρας", "Επαγγελματίας ξεναγός", "Ελεύθερος χρόνος"] },
    included: { en: ["Air-conditioned bus transport", "English-speaking guide", "Entrance fee", "Hotel pickup option"], el: ["Μεταφορά με λεωφορείο", "Αγγλόφωνος ξεναγός", "Εισιτήριο εισόδου", "Παραλαβή από ξενοδοχείο"] },
    meetingPoint: { en: "Syntagma Square, Athens", el: "Πλατεία Συντάγματος" },
    groupSize: "Up to 30 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ CRETE ═══
  {
    slug: "crete-cooking-class-traditional-village",
    title: { en: "Cretan Cooking Class & Olive Oil Tasting in Traditional Village", el: "Μάθημα Κρητικής Μαγειρικής & Γευσιγνωσία Ελαιολάδου" },
    shortDescription: { en: "Harvest fresh organic vegetables from the garden, cook authentic Cretan recipes in a family estate, and sample award-winning olive oil.", el: "Μαζέψτε βιολογικά λαχανικά, μαγειρέψτε κρητικές συνταγές και δοκιμάστε βραβευμένο ελαιόλαδο." },
    destination: "Crete",
    region: "Crete",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία" },
    duration: "4.5 hours",
    durationHours: 4.5,
    priceFrom: 85,
    priceLabel: { en: "from €85/person", el: "από €85/άτομο" },
    rating: 4.9,
    reviewCount: 940,
    image: "/images/crete.webp",
    highlights: { en: ["Cook 5 traditional dishes", "Award-winning olive oil tasting", "Multi-course lunch with wine", "Recipe book to take home"], el: ["Μαγειρέψτε 5 πιάτα", "Γευσιγνωσία βραβευμένου ελαιολάδου", "Γεύμα πολλών πιάτων", "Βιβλίο συνταγών"] },
    included: { en: ["All ingredients & tools", "Professional oil tasting", "Full lunch with wine & raki", "Recipe booklet"], el: ["Όλα τα υλικά & εργαλεία", "Επαγγελματική γευσιγνωσία", "Πλήρες γεύμα με κρασί & ρακή", "Βιβλιαράκι συνταγών"] },
    meetingPoint: { en: "Vamos Village, Apokoronas", el: "Χωριό Βάμος, Αποκόρωνας" },
    groupSize: "Up to 12 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    badge: "local-favorite",
    featured: true
  },
  {
    slug: "crete-knossos-archaeological-tour",
    title: { en: "Knossos Palace & Heraklion Archaeological Museum Guided Tour", el: "Ξενάγηση στο Παλάτι της Κνωσού & Μουσείο Ηρακλείου" },
    shortDescription: { en: "Explore the legendary Minoan Palace of Knossos with an archaeologist. See the throne room, frescoes, and the treasures of the Heraklion Museum.", el: "Εξερευνήστε το μινωικό ανάκτορο με αρχαιολόγο. Δείτε τον θρόνο, τις τοιχογραφίες και τους θησαυρούς του Μουσείου." },
    destination: "Crete",
    region: "Crete",
    type: "history",
    typeLabel: { en: "History & Archaeology", el: "Ιστορία" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 60,
    priceLabel: { en: "from €60/person", el: "από €60/άτομο" },
    rating: 4.7,
    reviewCount: 3200,
    image: "/images/crete.webp",
    highlights: { en: ["Minoan Palace of Knossos", "Throne Room & frescoes", "Heraklion Museum artifacts", "Skip-the-line entry"], el: ["Μινωικό ανάκτορο Κνωσού", "Θρόνος & τοιχογραφίες", "Εκθέματα Μουσείου Ηρακλείου", "Είσοδος χωρίς ουρά"] },
    included: { en: ["Licensed archaeological guide", "Skip-the-line tickets", "Museum entrance fee", "Audio headsets"], el: ["Πιστοποιημένος αρχαιολόγος", "Εισιτήρια χωρίς ουρά", "Είσοδος μουσείου", "Ακουστικά"] },
    meetingPoint: { en: "Knossos Palace main entrance", el: "Κεντρική είσοδος Κνωσού" },
    groupSize: "Up to 18 guests",
    difficulty: "easy",
    languages: ["en", "el", "fr"],
    badge: "bestseller",
    featured: false
  },
  {
    slug: "crete-samaria-gorge-hiking",
    title: { en: "Samaria Gorge Full Day Hiking Adventure from Chania", el: "Πεζοπορία στο Φαράγγι της Σαμαριάς από τα Χανιά" },
    shortDescription: { en: "Hike through Europe's longest gorge (16 km) in the White Mountains. Swim at the stunning beach of Agia Roumeli and take the ferry back.", el: "Πεζοπορήστε στο μεγαλύτερο φαράγγι της Ευρώπης, κολυμπήστε στην Αγία Ρουμέλη και επιστρέψτε με πλοίο." },
    destination: "Crete",
    region: "Crete",
    type: "adventure",
    typeLabel: { en: "Adventure & Hiking", el: "Περιπέτεια" },
    duration: "10 hours",
    durationHours: 10,
    priceFrom: 35,
    priceLabel: { en: "from €35/person", el: "από €35/άτομο" },
    rating: 4.6,
    reviewCount: 4100,
    image: "/images/crete.webp",
    highlights: { en: ["16 km gorge hike", "White Mountains scenery", "Swim at Agia Roumeli", "Ferry ride across Libyan Sea"], el: ["Πεζοπορία 16 χλμ", "Τοπία Λευκών Ορέων", "Κολύμπι στην Αγία Ρουμέλη", "Διαδρομή με πλοίο"] },
    included: { en: ["Bus transport from Chania", "National park entrance fee", "Licensed hiking guide", "Ferry ticket to Chora Sfakion"], el: ["Μεταφορά από Χανιά", "Εισιτήριο Εθνικού Δρυμού", "Πιστοποιημένος οδηγός", "Εισιτήριο πλοίου"] },
    meetingPoint: { en: "Chania central bus station", el: "Κεντρικός σταθμός λεωφορείων Χανίων" },
    groupSize: "Up to 25 guests",
    difficulty: "challenging",
    languages: ["en", "el", "de"],
    badge: "bestseller",
    featured: false
  },

  // ═══ MYKONOS ═══
  {
    slug: "mykonos-delos-guided-archaeological-tour",
    title: { en: "Delos Island Sacred Archaeological Guided Tour from Mykonos", el: "Ξενάγηση στην Ιερή Δήλο από τη Μύκονο" },
    shortDescription: { en: "Take a 30-minute boat trip to the uninhabited sacred island of Delos, birthplace of Apollo and Artemis, and explore its spectacular ruins.", el: "Κάντε 30' με καΐκι στην ιερή Δήλο και εξερευνήστε τα ερείπια με αρχαιολόγο." },
    destination: "Mykonos",
    region: "Cyclades",
    type: "history",
    typeLabel: { en: "History & Archaeology", el: "Ιστορία" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 65,
    priceLabel: { en: "from €65/person", el: "από €65/άτομο" },
    rating: 4.7,
    reviewCount: 1850,
    image: "/images/mykonos.webp",
    highlights: { en: ["Terrace of the Lions", "Ancient theatre ruins", "Archaeological museum", "Scenic boat cruise"], el: ["Οδός Λεόντων", "Αρχαίο θέατρο", "Αρχαιολογικό μουσείο", "Κρουαζιέρα"] },
    included: { en: ["Round-trip boat tickets", "Licensed guide", "Entrance fee to Delos", "Audio headsets"], el: ["Εισιτήρια πλοίου μετ' επιστροφής", "Πιστοποιημένος ξεναγός", "Εισιτήριο Δήλου", "Ακουστικά"] },
    meetingPoint: { en: "Mykonos Old Port", el: "Παλιό Λιμάνι Μυκόνου" },
    groupSize: "Up to 25 guests",
    difficulty: "moderate",
    languages: ["en", "el", "fr"],
    badge: "bestseller",
    featured: true
  },
  {
    slug: "mykonos-catamaran-cruise",
    title: { en: "Mykonos Luxury Catamaran Cruise with BBQ & Open Bar", el: "Πολυτελής Κρουαζιέρα με Καταμαράν στη Μύκονο" },
    shortDescription: { en: "Sail around the southern coast of Mykonos on a luxury catamaran. Stop at Rhenia island for swimming and enjoy a BBQ lunch prepared by the crew.", el: "Πλεύστε γύρω από τη Μύκονο με πολυτελές καταμαράν. Σταματήστε στη Ρήνεια και απολαύστε BBQ." },
    destination: "Mykonos",
    region: "Cyclades",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 120,
    priceLabel: { en: "from €120/person", el: "από €120/άτομο" },
    rating: 4.8,
    reviewCount: 890,
    image: "/images/mykonos.webp",
    highlights: { en: ["Luxury catamaran experience", "Swimming at Rhenia island", "BBQ lunch & open bar", "Snorkeling equipment"], el: ["Πολυτελές καταμαράν", "Κολύμπι στη Ρήνεια", "BBQ & open bar", "Εξοπλισμός snorkeling"] },
    included: { en: ["Catamaran cruise", "BBQ lunch", "Open bar with wine, beer, cocktails", "Snorkeling gear", "Hotel pickup"], el: ["Κρουαζιέρα με καταμαράν", "BBQ γεύμα", "Open bar", "Εξοπλισμός snorkeling", "Παραλαβή"] },
    meetingPoint: { en: "Mykonos Old Port Marina", el: "Μαρίνα Παλιού Λιμανιού" },
    groupSize: "Up to 14 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ KEFALONIA ═══
  {
    slug: "kefalonia-melissani-lake-myrtos-beach-day-trip",
    title: { en: "Kefalonia Highlights: Melissani, Drogarati & Myrtos Viewpoint", el: "Τα Highlights της Κεφαλονιάς: Μελισσάνη, Δρογκαράτη & Μύρτος" },
    shortDescription: { en: "Ride a boat inside Melissani underground lake, see ancient stalactites in Drogarati Cave, and take photos at the iconic Myrtos Beach viewpoint.", el: "Βαρκάδα στη λίμνη Μελισσάνης, σταλακτίτες στη Δρογκαράτη και φωτογραφία στον Μύρτο." },
    destination: "Kefalonia",
    region: "Ionian Islands",
    type: "day-trip",
    typeLabel: { en: "Full Day Trip", el: "Ολοήμερη Εκδρομή" },
    duration: "6 hours",
    durationHours: 6,
    priceFrom: 55,
    priceLabel: { en: "from €55/person", el: "από €55/άτομο" },
    rating: 4.8,
    reviewCount: 1220,
    image: "/images/kefalonia.webp",
    highlights: { en: ["Melissani cave rowboat ride", "Drogarati stalactite cave", "Myrtos Beach viewpoint", "Agia Efimia village lunch"], el: ["Βαρκάδα στη Μελισσάνη", "Σπήλαιο Δρογκαράτη", "Θέα Μύρτου", "Γεύμα στην Αγία Ευφημία"] },
    included: { en: ["Luxury bus transport", "Local expert guide", "Rowboat in Melissani cave", "Hotel pickup/drop-off"], el: ["Μεταφορά με λεωφορείο", "Τοπικός ξεναγός", "Βαρκάδα στη Μελισσάνη", "Παραλαβή από ξενοδοχείο"] },
    meetingPoint: { en: "Argostoli Port terminal", el: "Λιμάνι Αργοστολίου" },
    groupSize: "Up to 20 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    badge: "local-favorite",
    featured: true
  },
  {
    slug: "kefalonia-boat-cruise-ithaca",
    title: { en: "Kefalonia Full-Day Boat Cruise to Ithaca & Fiskardo", el: "Ολοήμερη Κρουαζιέρα σε Ιθάκη & Φισκάρδο" },
    shortDescription: { en: "Sail across the Ionian Sea to the mythical island of Ithaca. Swim in secluded bays, visit the picturesque village of Fiskardo, and enjoy a fresh seafood lunch.", el: "Πλεύστε στο Ιόνιο προς την Ιθάκη. Κολυμπήστε σε κρυφές παραλίες και απολαύστε φρέσκο ψάρι στο Φισκάρδο." },
    destination: "Kefalonia",
    region: "Ionian Islands",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "8 hours",
    durationHours: 8,
    priceFrom: 95,
    priceLabel: { en: "from €95/person", el: "από €95/άτομο" },
    rating: 4.7,
    reviewCount: 670,
    image: "/images/kefalonia.webp",
    highlights: { en: ["Sail to Ithaca island", "Swim in secluded bays", "Visit Fiskardo village", "Seafood lunch onboard"], el: ["Ιστιοπλοΐα στην Ιθάκη", "Κολύμπι σε κρυφές παραλίες", "Επίσκεψη Φισκάρδου", "Γεύμα με ψάρι"] },
    included: { en: ["Boat cruise", "Seafood lunch", "Snorkeling equipment", "Beach towels"], el: ["Κρουαζιέρα", "Γεύμα με θαλασσινά", "Εξοπλισμός snorkeling", "Πετσέτες παραλίας"] },
    meetingPoint: { en: "Fiskardo Port", el: "Λιμάνι Φισκάρδου" },
    groupSize: "Up to 30 guests",
    difficulty: "easy",
    languages: ["en", "el", "it"],
    featured: false
  },

  // ═══ METEGRA ═══
  {
    slug: "meteora-sunset-monasteries-tour",
    title: { en: "Meteora Sunset Tour: Monasteries, Hermit Caves & Views", el: "Εκδρομή στο Ηλιοβασίλεμα των Μετεώρων" },
    shortDescription: { en: "Visit cliff-top Byzantine monasteries, explore ancient hermit caves, and watch the sunset paint the rock pillars in golden light.", el: "Επισκεφθείτε μοναστήρια, σπηλιές ασκητών και θαυμάστε το ηλιοβασίλεμα." },
    destination: "Meteora",
    region: "Thessaly",
    type: "nature",
    typeLabel: { en: "Nature & Cultural", el: "Φύση & Πολιτισμός" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 45,
    priceLabel: { en: "from €45/person", el: "από €45/άτομο" },
    rating: 4.9,
    reviewCount: 2210,
    image: "/images/meteora.webp",
    highlights: { en: ["Sunset from best viewpoints", "Visit 1-2 monasteries", "Hidden hermit caves", "Monk history stories"], el: ["Ηλιοβασίλεμα από καλύτερα σημεία", "Επίσκεψη μοναστηριών", "Ασκητικές σπηλιές", "Ιστορία μοναχών"] },
    included: { en: ["VIP minibus transport", "Local guide", "Free Wi-Fi", "Hotel pickup"], el: ["Μεταφορά με VIP μίνιμπας", "Τοπικός ξεναγός", "Δωρεάν Wi-Fi", "Παραλαβή"] },
    meetingPoint: { en: "Kalampaka train station", el: "Σιδηροδρομικός σταθμός Καλαμπάκας" },
    groupSize: "Up to 15 guests",
    difficulty: "easy",
    languages: ["en", "el", "es"],
    badge: "bestseller",
    featured: true
  },
  {
    slug: "meteora-hiking-adventure",
    title: { en: "Meteora Hiking & Rock Climbing Adventure", el: "Πεζοπορία & Αναρρίχηση στα Μετέωρα" },
    shortDescription: { en: "Explore hidden trails between the giant rock pillars. For the adventurous, try rock climbing on authentic Meteora routes with a professional instructor.", el: "Εξερευνήστε κρυφά μονοπάτια. Για τους τολμηρούς, αναρριχηθείτε σε αυθεντικές διαδρομές." },
    destination: "Meteora",
    region: "Thessaly",
    type: "adventure",
    typeLabel: { en: "Adventure & Hiking", el: "Περιπέτεια" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 70,
    priceLabel: { en: "from €70/person", el: "από €70/άτομο" },
    rating: 4.8,
    reviewCount: 340,
    image: "/images/meteora.webp",
    highlights: { en: ["Hidden trails between pillars", "Rock climbing routes", "Professional instructor", "Panoramic views"], el: ["Κρυφά μονοπάτια", "Διαδρομές αναρρίχησης", "Επαγγελματίας εκπαιδευτής", "Πανοραμική θέα"] },
    included: { en: ["Experienced hiking guide", "Climbing equipment", "Safety harness & helmet", "Hotel transfer"], el: ["Έμπειρος οδηγός", "Εξοπλισμός αναρρίχησης", "Ζώνη & κράνος", "Μεταφορά"] },
    meetingPoint: { en: "Kastraki Village square", el: "Πλατεία Καστρακίου" },
    groupSize: "Up to 8 guests",
    difficulty: "challenging",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ ZAKYNTHOS ═══
  {
    slug: "zakynthos-navagio-shipwreck-blue-caves",
    title: { en: "Zakynthos: Navagio Shipwreck & Blue Caves Speedboat Tour", el: "Ζάκυνθος: Ναυάγιο & Γαλάζιες Σπηλιές με Ταχύπλοο" },
    shortDescription: { en: "Hop on a speedboat to Zakynthos' most famous landmarks. Swim inside the glowing Blue Caves and walk the white sands of Shipwreck beach.", el: "Επιβιβαστείτε σε ταχύπλοο για το Ναυάγιο και τις Γαλάζιες Σπηλιές." },
    destination: "Zakynthos",
    region: "Ionian Islands",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "4.5 hours",
    durationHours: 4.5,
    priceFrom: 50,
    priceLabel: { en: "from €50/person", el: "από €50/άτομο" },
    rating: 4.6,
    reviewCount: 2150,
    image: "/images/zakynthos.webp",
    highlights: { en: ["Swim inside Blue Caves", "Shipwreck beach access", "Speedboat ride", "Turtle spotting in Marathias"], el: ["Γαλάζιες σπηλιές", "Παραλία Ναυαγίου", "Ταχύπλοο", "Χελώνες Caretta-Caretta"] },
    included: { en: ["Speedboat with skipper", "Snorkeling masks", "Hotel pickup", "Beach time at Navagio"], el: ["Ταχύπλοο με καπετάνιο", "Μάσκες snorkeling", "Παραλαβή", "Χρόνος στο Ναυάγιο"] },
    meetingPoint: { en: "Porto Vromi port or hotel pickup", el: "Λιμάνι Πόρτο Βρώμη" },
    groupSize: "Up to 20 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    badge: "bestseller",
    featured: false
  },

  // ═══ RHODES ═══
  {
    slug: "rhodes-medieval-town-private-walking-tour",
    title: { en: "Rhodes Medieval City Private Walking Tour with Licensed Guide", el: "Ιδιωτική Ξενάγηση στη Μεσαιωνική Πόλη της Ρόδου" },
    shortDescription: { en: "Step inside the largest active medieval city in Europe. Walk the Street of the Knights, visit the Palace of the Grand Master, and discover hidden Byzantine corners.", el: "Περπατήστε στην Οδό των Ιπποτών και το Παλάτι του Μεγάλου Μαγίστρου." },
    destination: "Rhodes",
    region: "Dodecanese",
    type: "cultural",
    typeLabel: { en: "Cultural & Walking", el: "Πολιτισμός" },
    duration: "3 hours",
    durationHours: 3,
    priceFrom: 120,
    priceLabel: { en: "from €120/group", el: "από €120/γκρουπ" },
    rating: 4.9,
    reviewCount: 340,
    image: "/images/rhodes.webp",
    highlights: { en: ["Private tour", "Palace of the Grand Master", "Street of the Knights", "Byzantine & Ottoman history"], el: ["Ιδιωτική ξενάγηση", "Παλάτι Μεγάλου Μαγίστρου", "Οδός Ιπποτών", "Βυζαντινή ιστορία"] },
    included: { en: ["Licensed guide for your party", "Skip-the-line palace tickets", "Tailored recommendations"], el: ["Πιστοποιημένος ξεναγός", "Εισιτήρια χωρίς ουρά", "Προτάσεις διαμονής"] },
    meetingPoint: { en: "Marine Gate, Medieval Town", el: "Θαλασσινή Πύλη, Παλιά Πόλη" },
    groupSize: "Private (Up to 8)",
    difficulty: "easy",
    languages: ["en", "el", "de", "fr"],
    badge: "exclusive",
    featured: false
  },
  {
    slug: "rhodes-lindos-acropolis-tour",
    title: { en: "Lindos Acropolis & Traditional Village Tour", el: "Ξενάγηση στην Ακρόπολη της Λίνδου" },
    shortDescription: { en: "Climb to the ancient Acropolis of Lindos with panoramic views of St. Paul's Bay. Explore the whitewashed village streets and charming squares.", el: "Ανεβείτε στην αρχαία Ακρόπολη της Λίνδου και εξερευνήστε το γραφικό χωριό." },
    destination: "Rhodes",
    region: "Dodecanese",
    type: "history",
    typeLabel: { en: "History & Archaeology", el: "Ιστορία" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 50,
    priceLabel: { en: "from €50/person", el: "από €50/άτομο" },
    rating: 4.6,
    reviewCount: 1780,
    image: "/images/rhodes.webp",
    highlights: { en: ["Lindos Acropolis views", "St. Paul's Bay panorama", "Traditional village walk", "Ancient Greek & medieval history"], el: ["Ακρόπολη Λίνδου", "Όρμος Αγίου Παύλου", "Παραδοσιακό χωριό", "Αρχαία & μεσαιωνική ιστορία"] },
    included: { en: ["Bus transport from Rhodes Town", "Licensed guide", "Entrance fee", "Free time in Lindos village"], el: ["Λεωφορείο από Ρόδο", "Πιστοποιημένος ξεναγός", "Εισιτήριο", "Ελεύθερος χρόνος"] },
    meetingPoint: { en: "Eleftherias Square, Rhodes Town", el: "Πλατεία Ελευθερίας, Πόλη Ρόδου" },
    groupSize: "Up to 20 guests",
    difficulty: "moderate",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ CORFU ═══
  {
    slug: "corfu-old-town-walking-food-tour",
    title: { en: "Corfu Old Town Walking Food Tour with Tastings", el: "Γαστρονομική Περιήγηση στην Παλιά Πόλη της Κέρκυρας" },
    shortDescription: { en: "Explore Corfu's Venetian Old Town through its flavors: taste pastitsada, kumquat liqueur, local wines, and traditional olive oil.", el: "Γνωρίστε την Κέρκυρα μέσα από τις γεύσεις της. Δοκιμάστε παστιτσάδα, κουμ κουάτ και τοπικό κρασί." },
    destination: "Corfu",
    region: "Ionian Islands",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία" },
    duration: "3 hours",
    durationHours: 3,
    priceFrom: 55,
    priceLabel: { en: "from €55/person", el: "από €55/άτομο" },
    rating: 4.7,
    reviewCount: 920,
    image: "/images/corfu.webp",
    highlights: { en: ["10+ tastings", "Venetian Old Town", "Kumquat liqueur tasting", "Local wine & cheese"], el: ["10+ γεύσεις", "Ενετική Παλιά Πόλη", "Γεύση κουμ κουάτ", "Τοπικό κρασί & τυρί"] },
    included: { en: ["Food guide", "All tastings (full meal)", "Kumquat distillery visit", "Wine tasting"], el: ["Οδηγός γαστρονομίας", "Όλες οι δοκιμές", "Επίσκεψη αποστακτηρίου", "Οινογνωσία"] },
    meetingPoint: { en: "Liston Arcade, Corfu Town", el: "Λιστόν, Κέρκυρα" },
    groupSize: "Up to 10 guests",
    difficulty: "easy",
    languages: ["en", "el", "it"],
    featured: false
  },
  {
    slug: "corfu-paxos-antipaxos-boat-trip",
    title: { en: "Corfu Day Trip: Paxos & Antipaxos Blue Caves Boat Cruise", el: "Ημερήσια Κρουαζιέρα σε Παξούς & Αντίπαξους" },
    shortDescription: { en: "Cruise to the turquoise waters of Paxos and Antipaxos. Swim in the famous Blue Caves and explore the charming harbour village of Gaios.", el: "Κρουαζιέρα στα τιρκουάζ νερά των Παξών. Κολυμπήστε στις Γαλάζιες Σπηλιές." },
    destination: "Corfu",
    region: "Ionian Islands",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "9 hours",
    durationHours: 9,
    priceFrom: 80,
    priceLabel: { en: "from €80/person", el: "από €80/άτομο" },
    rating: 4.5,
    reviewCount: 1450,
    image: "/images/corfu.webp",
    highlights: { en: ["Blue Caves swimming", "Paxos & Antipaxos", "Gaios village visit", "Lunch on board"], el: ["Γαλάζιες Σπηλιές", "Παξοί & Αντίπαξοι", "Γάιος", "Γεύμα στο πλοίο"] },
    included: { en: ["Boat cruise", "Swimming stops", "Lunch", "Beach time"], el: ["Κρουαζιέρα", "Στάσεις για μπάνιο", "Γεύμα", "Χρόνος σε παραλία"] },
    meetingPoint: { en: "Corfu New Port", el: "Νέο Λιμάνι Κέρκυρας" },
    groupSize: "Up to 40 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ THESSALONIKI ═══
  {
    slug: "thessaloniki-food-walking-tour",
    title: { en: "Thessaloniki Food Tour: The Culinary Capital of Greece", el: "Γαστρονομική Περιήγηση στη Θεσσαλονίκη" },
    shortDescription: { en: "Sample bougatsa, souvlaki, and the best street food of Thessaloniki. Explore the Modiano Market, Ano Poli, and waterfront tavernas.", el: "Δοκιμάστε μπουγάτσα, σουβλάκι και street food στην αγορά Μοδιάνο." },
    destination: "Thessaloniki",
    region: "Macedonia",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία" },
    duration: "3.5 hours",
    durationHours: 3.5,
    priceFrom: 45,
    priceLabel: { en: "from €45/person", el: "από €45/άτομο" },
    rating: 4.7,
    reviewCount: 860,
    image: "/images/thessaloniki.webp",
    highlights: { en: ["Modiano Market", "Bougatsa & souvlaki tasting", "Ano Poli (Upper Town)", "Waterfront tavernas"], el: ["Αγορά Μοδιάνο", "Μπουγάτσα & σουβλάκι", "Άνω Πόλη", "Παραλιακές ταβέρνες"] },
    included: { en: ["Local food guide", "8+ food tastings", "Wine/beer pairing", "Modiano Market tour"], el: ["Τοπικός οδηγός", "8+ γεύσεις", "Συνοδεία κρασιού/μπίρας", "Περιήγηση Μοδιάνο"] },
    meetingPoint: { en: "Aristotelous Square", el: "Πλατεία Αριστοτέλους" },
    groupSize: "Up to 10 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ HALKIDIKI ═══
  {
    slug: "halkidiki-mount-athos-cruise",
    title: { en: "Halkidiki: Mount Athos & Ammouliani Island Cruise", el: "Κρουαζιέρα στο Άγιο Όρος & Αμμουλιανή" },
    shortDescription: { en: "Cruise along the breathtaking coast of Mount Athos, see the Byzantine monasteries from the sea, and swim at Ammouliani island.", el: "Κρουαζιέρα στο Άγιο Όρος με θέα στις μονές και κολύμπι στην Αμμουλιανή." },
    destination: "Halkidiki",
    region: "Macedonia",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "7 hours",
    durationHours: 7,
    priceFrom: 65,
    priceLabel: { en: "from €65/person", el: "από €65/άτομο" },
    rating: 4.6,
    reviewCount: 780,
    image: "/images/halkidiki.webp",
    highlights: { en: ["Mount Athos monasteries", "Ammouliani swimming", "Blue Lagoon stop", "Lunch on board"], el: ["Μονές Αγίου Όρους", "Κολύμπι Αμμουλιανή", "Μπλε Λιμνοθάλασσα", "Γεύμα"] },
    included: { en: ["Boat cruise", "Lunch", "Hotel pickup", "English guide"], el: ["Κρουαζιέρα", "Γεύμα", "Παραλαβή", "Αγγλόφωνος ξεναγός"] },
    meetingPoint: { en: "Ouranoupolis port", el: "Λιμάνι Ουρανούπολης" },
    groupSize: "Up to 50 guests",
    difficulty: "easy",
    languages: ["en", "el", "ru"],
    featured: false
  },

  // ═══ PAROS ═══
  {
    slug: "paros-antiparos-sailing-tour",
    title: { en: "Paros to Antiparos Sailing Catamaran Day Trip", el: "Ιστιοπλοϊκή Εκδρομή από Πάρο προς Αντίπαρο" },
    shortDescription: { en: "Sail across the crystal-clear strait to Antiparos. Swim in turquoise coves, explore the Venetian castle, and enjoy freshly caught seafood.", el: "Πλεύστε προς τον Αντίπαρο, κολυμπήστε σε τιρκουάζ όρμους και δοκιμάστε φρέσκο ψάρι." },
    destination: "Paros",
    region: "Cyclades",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "6 hours",
    durationHours: 6,
    priceFrom: 95,
    priceLabel: { en: "from €95/person", el: "από €95/άτομο" },
    rating: 4.8,
    reviewCount: 560,
    image: "/images/paros.webp",
    highlights: { en: ["Catamaran sailing", "Antiparos Venetian Castle", "Snorkeling in coves", "Seafood BBQ lunch"], el: ["Ιστιοπλοΐα", "Ενετικό Κάστρο Αντιπάρου", "Snorkeling", "BBQ με θαλασσινά"] },
    included: { en: ["Catamaran cruise", "BBQ lunch", "Open bar", "Snorkeling gear"], el: ["Κρουαζιέρα", "BBQ γεύμα", "Open bar", "Εξοπλισμός snorkeling"] },
    meetingPoint: { en: "Parikia Port, Paros", el: "Λιμάνι Παροικιάς" },
    groupSize: "Up to 12 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "paros-walking-tour-naoussa",
    title: { en: "Paros Walking Tour: Naoussa Harbor & Traditional Villages", el: "Πεζοπορική Περιήγηση στη Νάουσα & τα Χωριά της Πάρου" },
    shortDescription: { en: "Explore the whitewashed streets of Naoussa, Lefkes village, and the Byzantine walking trail with panoramic views.", el: "Εξερευνήστε τα γραφικά σοκάκια της Νάουσας και το παλιό μονοπάτι των Λευκών." },
    destination: "Paros",
    region: "Cyclades",
    type: "cultural",
    typeLabel: { en: "Cultural & Walking", el: "Πολιτισμός" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 40,
    priceLabel: { en: "from €40/person", el: "από €40/άτομο" },
    rating: 4.5,
    reviewCount: 420,
    image: "/images/paros.webp",
    highlights: { en: ["Naoussa fishing harbor", "Lefkes marble village", "Byzantine trail", "Panoramic viewpoints"], el: ["Ψαράδικο λιμάνι Νάουσας", "Λεύκες", "Βυζαντινό μονοπάτι", "Πανοραμική θέα"] },
    included: { en: ["Local walking guide", "Refreshments", "Hotel transfer from Parikia"], el: ["Τοπικός οδηγός", "Αναψυκτικά", "Μεταφορά από Παροικιά"] },
    meetingPoint: { en: "Naoussa central square", el: "Κεντρική πλατεία Νάουσας" },
    groupSize: "Up to 10 guests",
    difficulty: "moderate",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ MILOS ═══
  {
    slug: "milos-kleftiko-sailing-boat-tour",
    title: { en: "Milos Full Day Sailing to Kleftiko Caves & Sykia with BBQ", el: "Ολοήμερη Ιστιοπλοΐα στο Κλέφτικο & τη Συκιά" },
    shortDescription: { en: "Sail around Milos' volcanic coastline. Swim through Kleftiko's crystal pirate caves, explore Sykia Cave, and enjoy a BBQ on board.", el: "Κολυμπήστε στα κρυστάλλινα νερά του Κλέφτικου και απολαύστε BBQ." },
    destination: "Milos",
    region: "Cyclades",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "8 hours",
    durationHours: 8,
    priceFrom: 110,
    priceLabel: { en: "from €110/person", el: "από €110/άτομο" },
    rating: 4.9,
    reviewCount: 780,
    image: "/images/milos.webp",
    highlights: { en: ["Kleftiko pirate caves", "Sykia Cave swim", "Volcanic coastline", "BBQ cooked on board"], el: ["Κλέφτικο", "Σπήλαιο Συκιάς", "Ηφαιστειακή ακτογραμμή", "BBQ στο σκάφος"] },
    included: { en: ["Skipper & crew", "BBQ lunch & open bar", "GoPro underwater photos", "Snorkeling gear"], el: ["Καπετάνιος & πλήρωμα", "BBQ & open bar", "Υποβρύχιες φωτογραφίες", "Εξοπλισμός snorkeling"] },
    meetingPoint: { en: "Adamantas Marina, Milos", el: "Μαρίνα Αδάμαντα, Μήλος" },
    groupSize: "Up to 10 guests",
    difficulty: "moderate",
    languages: ["en", "el", "it"],
    badge: "new",
    featured: false
  },

  // ═══ NAFPLIO ═══
  {
    slug: "nafplio-mycenae-epidaurus-day-trip",
    title: { en: "Mycenae & Epidaurus Full Day Tour from Nafplio", el: "Ολοήμερη Εκδρομή σε Μυκήνες & Επίδαυρο" },
    shortDescription: { en: "Walk through the Lion Gate of Mycenae, explore the Tomb of Agamemnon, and marvel at the acoustics of the ancient Epidaurus Theatre.", el: "Περάστε από την Πύλη των Λεόντων, δείτε τον τάφο του Αγαμέμνονα και το Θέατρο της Επιδαύρου." },
    destination: "Nafplio",
    region: "Peloponnese",
    type: "history",
    typeLabel: { en: "History & Archaeology", el: "Ιστορία & Αρχαιολογία" },
    duration: "6 hours",
    durationHours: 6,
    priceFrom: 70,
    priceLabel: { en: "from €70/person", el: "από €70/άτομο" },
    rating: 4.8,
    reviewCount: 1580,
    image: "/images/nafplio.webp",
    highlights: { en: ["Lion Gate of Mycenae", "Treasury of Atreus", "Ancient Theatre of Epidaurus", "Nafplio Old Town walk"], el: ["Πύλη Λεόντων Μυκηνών", "Θησαυρός του Ατρέα", "Αρχαίο Θέατρο Επιδαύρου", "Παλιά Πόλη Ναυπλίου"] },
    included: { en: ["Licensed guide", "Air-conditioned transport", "Entrance fees", "Hotel pickup/drop-off"], el: ["Πιστοποιημένος ξεναγός", "Μεταφορά", "Εισιτήρια", "Παραλαβή/αποβίβαση"] },
    meetingPoint: { en: "Syntagma Square, Nafplio", el: "Πλατεία Συντάγματος, Ναύπλιο" },
    groupSize: "Up to 18 guests",
    difficulty: "moderate",
    languages: ["en", "el", "fr"],
    badge: "bestseller",
    featured: true
  },
  {
    slug: "nafplio-argolic-gulf-sailing-cruise",
    title: { en: "Argolic Gulf Sailing Cruise with Swim Stops & Lunch", el: "Ιστιοπλοΐα στον Αργολικό Κόλπο με Μπάνιο & Γεύμα" },
    shortDescription: { en: "Set sail across the Argolic Gulf from Nafplio, swim at secluded beaches on Bourtzi island, and enjoy a traditional Greek lunch on board.", el: "Αποπλεύστε από το Ναύπλιο, κολυμπήστε στο Μπούρτζι και απολαύστε ελληνικό γεύμα." },
    destination: "Nafplio",
    region: "Peloponnese",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 80,
    priceLabel: { en: "from €80/person", el: "από €80/άτομο" },
    rating: 4.7,
    reviewCount: 620,
    image: "/images/nafplio.webp",
    highlights: { en: ["Sailing the Argolic Gulf", "Swim at Bourtzi island", "Greek BBQ lunch", "Palamidi fortress views"], el: ["Ιστιοπλοΐα Αργολικού", "Κολύμπι στο Μπούρτζι", "BBB γεύμα", "Θέα Παλαμηδίου"] },
    included: { en: ["Skipper & crew", "BBQ lunch", "Snorkeling gear", "Beach towels"], el: ["Καπετάνιος & πλήρωμα", "BBQ γεύμα", "Εξοπλισμός snorkeling", "Πετσέτες"] },
    meetingPoint: { en: "Nafplio Marina", el: "Μαρίνα Ναυπλίου" },
    groupSize: "Up to 12 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "nafplio-walking-food-tour",
    title: { en: "Nafplio Walking Food Tour & Olive Oil Tasting", el: "Γαστρονομική Περιήγηση & Ελαιόλαδο στο Ναύπλιο" },
    shortDescription: { en: "Taste the best of Nafplio's cuisine: fresh seafood, local olive oil, artisan cheeses, and sweet pastries through the Venetian Old Town.", el: "Δοκιμάστε φρέσκο ψάρι, τοπικό ελαιόλαδο, τυριά και γλυκά στην παλιά πόλη." },
    destination: "Nafplio",
    region: "Peloponnese",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία" },
    duration: "3.5 hours",
    durationHours: 3.5,
    priceFrom: 48,
    priceLabel: { en: "from €48/person", el: "από €48/άτομο" },
    rating: 4.8,
    reviewCount: 430,
    image: "/images/nafplio.webp",
    highlights: { en: ["8+ local tastings", "Olive oil farm visit", "Venetian Old Town walk", "Local wine pairing"], el: ["8+ γεύσεις", "Επίσκεψη ελαιοτριβείου", "Περιήγηση Παλιάς Πόλης", "Συνοδεία κρασιού"] },
    included: { en: ["Local food guide", "All tastings", "Olive oil tasting", "Wine glass"], el: ["Οδηγός γαστρονομίας", "Όλες οι γεύσεις", "Γευσιγνωσία ελαιολάδου", "Ποτήρι κρασιού"] },
    meetingPoint: { en: "Kapodistrias Square, Nafplio", el: "Πλατεία Καποδίστρια, Ναύπλιο" },
    groupSize: "Up to 10 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ LESVOS ═══
  {
    slug: "lesvos-olive-oil-farm-tour",
    title: { en: "Lesvos Olive Oil Farm Tour with Tastings & Lunch", el: "Περιήγηση σε Ελαιοτριβείο με Γευσιγνωσία & Γεύμα" },
    shortDescription: { en: "Visit a family-run organic olive farm, learn the art of extra virgin olive oil production, and enjoy a farm-to-table lunch under ancient olive trees.", el: "Επισκεφθείτε βιολογικό ελαιοτριβείο και απολαύστε γεύμα κάτω από αιωνόβιες ελιές." },
    destination: "Lesvos",
    region: "North Aegean",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 60,
    priceLabel: { en: "from €60/person", el: "από €60/άτομο" },
    rating: 4.8,
    reviewCount: 340,
    image: "/images/lesvos.webp",
    highlights: { en: ["Organic olive farm", "EVOO production demo", "5-olive-oil tasting", "Farm-to-table lunch"], el: ["Βιολογικό ελαιοτριβείο", "Παραγωγή ελαιολάδου", "Γευσιγνωσία 5 ελαιολάδων", "Γεύμα με τοπικά προϊόντα"] },
    included: { en: ["Farm tour & guide", "Olive oil tasting flight", "Farm lunch with wine", "Take-home olive oil bottle"], el: ["Περιήγηση", "Γευσιγνωσία ελαιολάδου", "Γεύμα με κρασί", "Μπουκάλι ελαιολάδου"] },
    meetingPoint: { en: "Mytilene central square", el: "Κεντρική πλατεία Μυτιλήνης" },
    groupSize: "Up to 12 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    badge: "local-favorite",
    featured: false
  },
  {
    slug: "lesvos-petrified-forest-hiking",
    title: { en: "Lesvos Petrified Forest & Sigri Geopark Hiking Tour", el: "Πεζοπορία στο Απολιθωμένο Δάσος & Γεωπάρκο Σίγρι" },
    shortDescription: { en: "Hike through the UNESCO Petrified Forest of Lesvos, see 20-million-year-old fossilized trees, and visit the Natural History Museum in Sigri.", el: "Πεζοπορήστε στο Απολιθωμένο Δάσος και επισκεφθείτε το Μουσείο Φυσικής Ιστορίας." },
    destination: "Lesvos",
    region: "North Aegean",
    type: "nature",
    typeLabel: { en: "Nature & Cultural", el: "Φύση & Πολιτισμός" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 45,
    priceLabel: { en: "from €45/person", el: "από €45/άτομο" },
    rating: 4.6,
    reviewCount: 290,
    image: "/images/lesvos.webp",
    highlights: { en: ["UNESCO Petrified Forest", "20-million-year-old fossils", "Natural History Museum", "Coastal hiking trail"], el: ["Απολιθωμένο Δάσος UNESCO", "Απολιθώματα 20 εκατ. ετών", "Μουσείο Φυσικής Ιστορίας", "Παράκτιο μονοπάτι"] },
    included: { en: ["Licensed hiking guide", "Museum entrance fee", "Transport from Mytilene", "Snack pack"], el: ["Πιστοποιημένος οδηγός", "Εισιτήριο μουσείου", "Μεταφορά από Μυτιλήνη", "Σνακ"] },
    meetingPoint: { en: "Mytilene bus station", el: "Σταθμός λεωφορείων Μυτιλήνης" },
    groupSize: "Up to 15 guests",
    difficulty: "moderate",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "lesvos-molyvos-village-ouzo-tasting",
    title: { en: "Molyvos Village Walk & Ouzo Distillery Tasting Tour", el: "Περιήγηση στο Μόλυβο & Γευσιγνωσία Ούζου" },
    shortDescription: { en: "Wander the cobblestone streets of Molyvos, visit the Genoese castle, and taste ouzo at a traditional distillery with local meze pairings.", el: "Περπατήστε στο Μόλυβο, δείτε το κάστρο και δοκιμάστε ούζο με μεζέ." },
    destination: "Lesvos",
    region: "North Aegean",
    type: "cultural",
    typeLabel: { en: "Cultural & Walking", el: "Πολιτισμός" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 38,
    priceLabel: { en: "from €38/person", el: "από €38/άτομο" },
    rating: 4.7,
    reviewCount: 510,
    image: "/images/lesvos.webp",
    highlights: { en: ["Molyvos cobblestone alleys", "Genoese castle views", "Ouzo distillery visit", "Meze & ouzo pairing"], el: ["Σοκάκια Μολύβου", "Θέα από το κάστρο", "Επίσκεψη αποστακτηρίου", "Ούζο & μεζές"] },
    included: { en: ["Local walking guide", "Ouzo distillery tour", "Ouzo & meze tasting", "Hotel transfer"], el: ["Τοπικός οδηγός", "Επίσκεψη αποστακτηρίου", "Γευσιγνωσία ούζου", "Μεταφορά"] },
    meetingPoint: { en: "Molyvos central square", el: "Κεντρική πλατεία Μολύβου" },
    groupSize: "Up to 10 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ MONEMVASIA ═══
  {
    slug: "monemvasia-castle-walking-tour",
    title: { en: "Monemvasia Medieval Castle & Upper Town Walking Tour", el: "Ξενάγηση στο Κάστρο & την Άνω Πόλη της Μονεμβασιάς" },
    shortDescription: { en: "Step back in time walking through the fortified medieval city of Monemvasia. Climb to the Upper Town for breathtaking sea views and visit the Agia Sophia church.", el: "Γυρίστε πίσω στον χρόνο στην καστροπολιτεία της Μονεμβασιάς." },
    destination: "Monemvasia",
    region: "Peloponnese",
    type: "history",
    typeLabel: { en: "History & Archaeology", el: "Ιστορία" },
    duration: "3 hours",
    durationHours: 3,
    priceFrom: 35,
    priceLabel: { en: "from €35/person", el: "από €35/άτομο" },
    rating: 4.7,
    reviewCount: 870,
    image: "/images/monemvasia.webp",
    highlights: { en: ["Medieval fortified city", "Upper Town climb", "Agia Sophia church", "Panoramic sea views"], el: ["Μεσαιωνική καστροπολιτεία", "Άνω Πόλη", "Αγία Σοφία", "Πανοραμική θέα"] },
    included: { en: ["Licensed guide", "Entrance to Agia Sophia", "Walking tour", "Historical booklet"], el: ["Πιστοποιημένος ξεναγός", "Είσοδος Αγίας Σοφίας", "Περιήγηση", "Ιστορικό φυλλάδιο"] },
    meetingPoint: { en: "Main gate of Monemvasia fortress", el: "Κεντρική πύλη κάστρου Μονεμβασιάς" },
    groupSize: "Up to 15 guests",
    difficulty: "moderate",
    languages: ["en", "el", "fr"],
    badge: "local-favorite",
    featured: false
  },
  {
    slug: "monemvasia-wine-tasting-day-trip",
    title: { en: "Monemvasia Wine Tasting & Coastal Village Day Trip", el: "Οινογνωσία & Παράκτια Περιήγηση στη Μονεμβασιά" },
    shortDescription: { en: "Visit family wineries in the surrounding hills of Monemvasia, taste the renowned Monemvasia-Malvasia wines, and explore the charming coastal villages.", el: "Επισκεφθείτε οινοποιεία και δοκιμάστε τα περίφημα κρασιά Malvasia." },
    destination: "Monemvasia",
    region: "Peloponnese",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 68,
    priceLabel: { en: "from €68/person", el: "από €68/άτομο" },
    rating: 4.8,
    reviewCount: 380,
    image: "/images/monemvasia.webp",
    highlights: { en: ["2 family wineries", "Malvasia wine tasting", "Coastal village visit", "Cheese & cold cuts"], el: ["2 οικογενειακά οινοποιεία", "Γεύση Malvasia", "Παράκτιο χωριό", "Τυριά & αλλαντικά"] },
    included: { en: ["Winemaker guide", "All tasting fees", "Lunch at seaside taverna", "Transport"], el: ["Οινοποιός ξεναγός", "Όλες οι γευσιγνωσίες", "Γεύμα σε ταβέρνα", "Μεταφορά"] },
    meetingPoint: { en: "Monemvasia central square", el: "Κεντρική πλατεία Μονεμβασιάς" },
    groupSize: "Up to 10 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ PARGA ═══
  {
    slug: "parga-venetian-castle-boat-tour",
    title: { en: "Parga Venetian Castle & Coastal Boat Tour with Swim", el: "Περιήγηση στο Ενετικό Κάστρο & Κρουαζιέρα" },
    shortDescription: { en: "Explore the Venetian castle of Parga overlooking the Ionian Sea, then board a boat to discover hidden coves, swim at Valtos Beach, and visit the islet of Panagia.", el: "Εξερευνήστε το κάστρο της Πάργας και ανακαλύψτε κρυφούς όρμους με βάρκα." },
    destination: "Parga",
    region: "Epirus",
    type: "cultural",
    typeLabel: { en: "Cultural & Walking", el: "Πολιτισμός" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 55,
    priceLabel: { en: "from €55/person", el: "από €55/άτομο" },
    rating: 4.6,
    reviewCount: 650,
    image: "/images/parga.webp",
    highlights: { en: ["Venetian castle & views", "Boat to Panagia islet", "Swim at Valtos", "Parga Old Town walk"], el: ["Ενετικό κάστρο", "Βάρκα στο νησάκι Παναγιά", "Κολύμπι στον Βάλτο", "Παλιά Πόλη Πάργας"] },
    included: { en: ["Castle entrance", "Boat cruise", "Snorkeling gear", "Hotel pickup"], el: ["Είσοδος κάστρου", "Κρουαζιέρα", "Εξοπλισμός snorkeling", "Παραλαβή"] },
    meetingPoint: { en: "Parga central square", el: "Κεντρική πλατεία Πάργας" },
    groupSize: "Up to 16 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "parga-acheron-springs-hiking",
    title: { en: "Acheron River Springs Hiking & Mythology Tour", el: "Πεζοπορία στις Πηγές του Αχέροντα" },
    shortDescription: { en: "Walk along the legendary Acheron River, known as the 'River of the Underworld'. Swim in the crystal-clear springs and learn about ancient Greek mythology.", el: "Περπατήστε δίπλα στον μυθικό Αχέροντα και κολυμπήστε στα κρυστάλλινα νερά." },
    destination: "Parga",
    region: "Epirus",
    type: "adventure",
    typeLabel: { en: "Adventure & Hiking", el: "Περιπέτεια" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 40,
    priceLabel: { en: "from €40/person", el: "από €40/άτομο" },
    rating: 4.7,
    reviewCount: 780,
    image: "/images/parga.webp",
    highlights: { en: ["Acheron River trail", "Crystal spring swim", "Nekromanteion ruins", "Mythology storytelling"], el: ["Μονοπάτι Αχέροντα", "Κολύμπι σε πηγές", "Νεκρομαντείο", "Μύθοι & θρύλοι"] },
    included: { en: ["Licensed hiking guide", "Transport from Parga", "Bottled water & snack", "Entrance fees"], el: ["Πιστοποιημένος οδηγός", "Μεταφορά", "Νερό & σνακ", "Εισιτήρια"] },
    meetingPoint: { en: "Parga bus station", el: "Σταθμός λεωφορείων Πάργας" },
    groupSize: "Up to 12 guests",
    difficulty: "moderate",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ DELPHI ═══
  {
    slug: "delphi-archaeological-site-guided-tour",
    title: { en: "Delphi Archaeological Site & Museum Guided Tour", el: "Ξενάγηση στον Αρχαιολογικό Χώρο & Μουσείο Δελφών" },
    shortDescription: { en: "Explore the Sanctuary of Apollo with a licensed archaeologist. See the Oracle of Delphi, the Temple of Apollo, and the treasures of the Delphi Museum.", el: "Εξερευνήστε το Ιερό του Απόλλωνα και δείτε το Μουσείο των Δελφών." },
    destination: "Delphi",
    region: "Central Greece",
    type: "history",
    typeLabel: { en: "History & Archaeology", el: "Ιστορία" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 55,
    priceLabel: { en: "from €55/person", el: "από €55/άτομο" },
    rating: 4.9,
    reviewCount: 3420,
    image: "/images/delphi.webp",
    highlights: { en: ["Temple of Apollo", "Oracle of Delphi site", "Delphi Museum treasures", "Panoramic mountain views"], el: ["Ναός Απόλλωνα", "Μαντείο Δελφών", "Μουσείο Δελφών", "Θέα στον Παρνασσό"] },
    included: { en: ["Licensed archaeological guide", "Skip-the-line entrance", "Museum tour", "Audio headsets"], el: ["Πιστοποιημένος αρχαιολόγος", "Είσοδος χωρίς ουρά", "Περιήγηση μουσείου", "Ακουστικά"] },
    meetingPoint: { en: "Delphi Archaeological Site entrance", el: "Είσοδος Αρχαιολογικού Χώρου Δελφών" },
    groupSize: "Up to 20 guests",
    difficulty: "moderate",
    languages: ["en", "el", "fr", "de"],
    badge: "bestseller",
    featured: true
  },
  {
    slug: "delphi-arachova-village-wine-tasting",
    title: { en: "Arachova Village & Wine Tasting Day Trip from Delphi", el: "Εκδρομή στην Αράχοβα & Οινογνωσία" },
    shortDescription: { en: "Visit the picturesque mountain village of Arachova, known for its vibrant streets and local crafts. Taste renowned Parnassus wines at a family winery with views of the valley.", el: "Επισκεφθείτε την Αράχοβα και δοκιμάστε κρασιά του Παρνασσού." },
    destination: "Delphi",
    region: "Central Greece",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 60,
    priceLabel: { en: "from €60/person", el: "από €60/άτομο" },
    rating: 4.7,
    reviewCount: 560,
    image: "/images/delphi.webp",
    highlights: { en: ["Arachova mountain village", "Parnassus winery", "6-wine tasting flight", "Local cheese pairing"], el: ["Αράχοβα", "Οινοποιείο Παρνασσού", "Γευσιγνωσία 6 κρασιών", "Συνοδεία τυριών"] },
    included: { en: ["Transport", "Winery tour & tasting", "English-speaking guide", "Local appetizers"], el: ["Μεταφορά", "Επίσκεψη & γευσιγνωσία", "Αγγλόφωνος ξεναγός", "Τοπικοί μεζέδες"] },
    meetingPoint: { en: "Delphi central bus stop", el: "Κεντρική στάση Δελφών" },
    groupSize: "Up to 12 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "delphi-hosios-loukas-monastery",
    title: { en: "Hosios Loukas Monastery & Distomo Day Trip", el: "Εκδρομή στην Οσία Λουκά & Δίστομο" },
    shortDescription: { en: "Visit the UNESCO-listed Hosios Loukas Monastery with its stunning Byzantine mosaics, then explore the historic town of Distomo known for its textile tradition.", el: "Επισκεφθείτε την Οσία Λουκά με τα βυζαντινά ψηφιδωτά και το Δίστομο." },
    destination: "Delphi",
    region: "Central Greece",
    type: "cultural",
    typeLabel: { en: "Cultural & Walking", el: "Πολιτισμός" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 50,
    priceLabel: { en: "from €50/person", el: "από €50/άτομο" },
    rating: 4.6,
    reviewCount: 340,
    image: "/images/delphi.webp",
    highlights: { en: ["UNESCO Hosios Loukas", "Byzantine mosaics", "Distomo textile town", "Mountain scenery"], el: ["Οσία Λουκά UNESCO", "Βυζαντινά ψηφιδωτά", "Δίστομο", "Ορεινό τοπίο"] },
    included: { en: ["Transport from Delphi", "Licensed guide", "Monastery entrance", "Free time in Distomo"], el: ["Μεταφορά", "Πιστοποιημένος ξεναγός", "Είσοδος μονής", "Ελεύθερος χρόνος"] },
    meetingPoint: { en: "Delphi central square", el: "Κεντρική πλατεία Δελφών" },
    groupSize: "Up to 15 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ SKIATHOS ═══
  {
    slug: "skiathos-koukounaries-boat-tour",
    title: { en: "Skiathos: Koukounaries Beach & Southern Coast Boat Cruise", el: "Κρουαζιέρα στην Κουκουναριές & Νότια Ακτή" },
    shortDescription: { en: "Sail along Skiathos' stunning southern coast, stop at the legendary Koukounaries Beach, swim in crystal-clear coves, and enjoy a BBQ lunch on board.", el: "Πλεύστε στη νότια ακτή της Σκιάθου, σταματήστε στην Κουκουναριές και απολαύστε BBQ." },
    destination: "Skiathos",
    region: "Sporades",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "6 hours",
    durationHours: 6,
    priceFrom: 75,
    priceLabel: { en: "from €75/person", el: "από €75/άτομο" },
    rating: 4.7,
    reviewCount: 890,
    image: "/images/skiathos.webp",
    highlights: { en: ["Koukounaries Beach stop", "Swim in secluded coves", "BBQ lunch on board", "Skiathos coastline views"], el: ["Παραλία Κουκουναριές", "Κρυφοί όρμοι", "BBQ στο σκάφος", "Ακτογραμμή Σκιάθου"] },
    included: { en: ["Boat cruise", "BBQ lunch & drinks", "Snorkeling equipment", "Beach time"], el: ["Κρουαζιέρα", "BBQ & ποτά", "Εξοπλισμός snorkeling", "Χρόνος σε παραλία"] },
    meetingPoint: { en: "Skiathos Old Port", el: "Παλιό Λιμάνι Σκιάθου" },
    groupSize: "Up to 20 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    badge: "bestseller",
    featured: false
  },
  {
    slug: "skiathos-lalaria-cruise-northern-coast",
    title: { en: "Skiathos: Lalaria Beach & Northern Coast Catamaran Cruise", el: "Κρουαζιέρα στη Λαλάρια & Βόρεια Ακτή με Καταμαράν" },
    shortDescription: { en: "Explore the iconic Lalaria Beach with its white pebbles and turquoise waters. Cruise along the dramatic northern coastline with hidden sea caves and rugged cliffs.", el: "Ανακαλύψτε την εμβληματική Λαλάρια και τις σπηλιές της βόρειας ακτής." },
    destination: "Skiathos",
    region: "Sporades",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 85,
    priceLabel: { en: "from €85/person", el: "από €85/άτομο" },
    rating: 4.8,
    reviewCount: 640,
    image: "/images/skiathos.webp",
    highlights: { en: ["Lalaria Beach & arch", "Northern sea caves", "Catamaran sailing", "Swim in crystal waters"], el: ["Παραλία Λαλάρια", "Θαλάσσιες σπηλιές", "Καταμαράν", "Κρυστάλλινα νερά"] },
    included: { en: ["Catamaran cruise", "Lunch & open bar", "Snorkeling gear", "Beach towels"], el: ["Κρουαζιέρα", "Γεύμα & open bar", "Εξοπλισμός snorkeling", "Πετσέτες"] },
    meetingPoint: { en: "Skiathos Old Port", el: "Παλιό Λιμάνι Σκιάθου" },
    groupSize: "Up to 14 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "skiathos-town-walking-food-tour",
    title: { en: "Skiathos Town Walking Tour with Local Food Tastings", el: "Περιήγηση στη Χώρα Σκιάθου & Γαστρονομία" },
    shortDescription: { en: "Explore the charming Skiathos Town with its whitewashed houses and vibrant bougainvillea. Taste local specialties at the central market and harbor tavernas.", el: "Γνωρίστε τη Χώρα Σκιάθου και δοκιμάστε τοπικές γεύσεις." },
    destination: "Skiathos",
    region: "Sporades",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία" },
    duration: "3 hours",
    durationHours: 3,
    priceFrom: 42,
    priceLabel: { en: "from €42/person", el: "από €42/άτομο" },
    rating: 4.6,
    reviewCount: 380,
    image: "/images/skiathos.webp",
    highlights: { en: ["Skiathos Town Old Port", "Bourtzi peninsula walk", "Central market tastings", "Harbor taverna lunch"], el: ["Παλιό Λιμάνι", "Περίπατος Μπούρτζι", "Αγορά", "Γεύμα σε ταβέρνα"] },
    included: { en: ["Local food guide", "7+ tastings", "Wine pairing", "Market tour"], el: ["Οδηγός γαστρονομίας", "7+ γεύσεις", "Συνοδεία κρασιού", "Περιήγηση αγοράς"] },
    meetingPoint: { en: "Skiathos Town clock tower", el: "Ρολόι Χώρας Σκιάθου" },
    groupSize: "Up to 10 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ THASSOS ═══
  {
    slug: "thassos-marble-beaches-tour",
    title: { en: "Thassos Marble Beaches & Giola Lagoon Safari Tour", el: "Σαφάρι στις Μαρμάρινες Παραλίες & τη Γκιόλα" },
    shortDescription: { en: "Drive through Thassos' pine-covered mountains to discover the island's famous marble beaches. Swim in the natural tidal pool of Giola Lagoon and visit traditional mountain villages.", el: "Ανακαλύψτε τις μαρμάρινες παραλίες της Θάσου και κολυμπήστε στη λιμνοθάλασσα Γκιόλα." },
    destination: "Thassos",
    region: "Eastern Macedonia",
    type: "nature",
    typeLabel: { en: "Nature & Cultural", el: "Φύση & Πολιτισμός" },
    duration: "7 hours",
    durationHours: 7,
    priceFrom: 55,
    priceLabel: { en: "from €55/person", el: "από €55/άτομο" },
    rating: 4.7,
    reviewCount: 520,
    image: "/images/thassos.webp",
    highlights: { en: ["Paradise Beach & Golden Beach", "Giola Lagoon swim", "Mountain villages", "Panoramic viewpoints"], el: ["Παραδείσου & Χρυσή Αμμουδιά", "Γκιόλα", "Ορεινά χωριά", "Πανοραμική θέα"] },
    included: { en: ["4x4 safari vehicle", "Local driver-guide", "Lunch at mountain taverna", "Pickup from hotel"], el: ["Όχημα 4x4", "Τοπικός οδηγός", "Γεύμα σε ταβέρνα", "Παραλαβή"] },
    meetingPoint: { en: "Limenas Port, Thassos", el: "Λιμάνι Λιμένα, Θάσος" },
    groupSize: "Up to 8 guests",
    difficulty: "easy",
    languages: ["en", "el", "bg"],
    featured: false
  },
  {
    slug: "thassos-island-boat-cruise",
    title: { en: "Thassos Full-Day Island Boat Cruise with BBQ Lunch", el: "Ολοήμερη Κρουαζιέρα στη Θάσο με BBQ" },
    shortDescription: { en: "Circumnavigate the emerald island of Thassos by boat. Stop at the most stunning beaches accessible only by sea, swim in remote bays, and feast on a BBQ lunch.", el: "Κάντε τον γύρο της Θάσου, κολυμπήστε σε απόμερες παραλίες και απολαύστε BBQ." },
    destination: "Thassos",
    region: "Eastern Macedonia",
    type: "boat",
    typeLabel: { en: "Boat Tour & Sailing", el: "Θαλάσσια Εκδρομή" },
    duration: "8 hours",
    durationHours: 8,
    priceFrom: 70,
    priceLabel: { en: "from €70/person", el: "από €70/άτομο" },
    rating: 4.5,
    reviewCount: 440,
    image: "/images/thassos.webp",
    highlights: { en: ["Full island circumnavigation", "Remote beach access", "Swim in emerald waters", "BBQ lunch on board"], el: ["Περίπλους νησιού", "Απόμερες παραλίες", "Κολύμπι", "BBQ στο σκάφος"] },
    included: { en: ["Boat cruise", "BBQ lunch", "Snorkeling gear", "Hotel pickup/drop-off"], el: ["Κρουαζιέρα", "BBQ γεύμα", "Εξοπλισμός snorkeling", "Παραλαβή/αποβίβαση"] },
    meetingPoint: { en: "Limenas Port, Thassos", el: "Λιμάνι Λιμένα, Θάσος" },
    groupSize: "Up to 30 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },

  // ═══ ADDITIONAL TOURS — EXISTING REGIONS ═══
  {
    slug: "santorini-ebike-adventure",
    title: { en: "Santorini E-Bike Adventure: Villages & Sunset Views", el: "E-Bike Περιπέτεια στη Σαντορίνη" },
    shortDescription: { en: "Ride electric bikes through Santorini's scenic trails, visit traditional villages like Pyrgos and Megalochori, and watch the sunset from a panoramic viewpoint.", el: "Οδηγήστε e-bike στα μονοπάτια της Σαντορίνης και απολαύστε το ηλιοβασίλεμα." },
    destination: "Santorini",
    region: "Cyclades",
    type: "adventure",
    typeLabel: { en: "Adventure & Hiking", el: "Περιπέτεια" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 75,
    priceLabel: { en: "from €75/person", el: "από €75/άτομο" },
    rating: 4.8,
    reviewCount: 410,
    image: "/images/santorini.webp",
    highlights: { en: ["E-bike through vineyards", "Pyrgos & Megalochori", "Sunset viewpoint", "Wine stop included"], el: ["E-bike σε αμπελώνες", "Πύργος & Μεγαλοχώρι", "Θέα ηλιοβασιλέματος", "Στάση για κρασί"] },
    included: { en: ["E-bike rental & helmet", "Local guide", "Refreshments", "Wine tasting stop"], el: ["E-bike & κράνος", "Τοπικός οδηγός", "Αναψυκτικά", "Στάση για κρασί"] },
    meetingPoint: { en: "Fira central square", el: "Κεντρική πλατεία Φηρών" },
    groupSize: "Up to 8 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "athens-rooftop-bar-nightlife-tour",
    title: { en: "Athens by Night: Rooftop Bars & Rooftop Dinner Tour", el: "Αθήνα τη Νύχτα: Rooftop Μπαρ & Δείπνο" },
    shortDescription: { en: "Experience Athens' vibrant nightlife with visits to the city's best rooftop bars overlooking the Acropolis. Enjoy a gourmet dinner with panoramic views and cocktails.", el: "Γνωρίστε τη νυχτερινή Αθήνα με rooftop μπαρ και θέα στην Ακρόπολη." },
    destination: "Athens",
    region: "Attica",
    type: "cultural",
    typeLabel: { en: "Cultural & Walking", el: "Πολιτισμός" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 90,
    priceLabel: { en: "from €90/person", el: "από €90/άτομο" },
    rating: 4.5,
    reviewCount: 230,
    image: "/images/athens.webp",
    highlights: { en: ["3 rooftop bars", "Acropolis night views", "Gourmet dinner", "Cocktail tasting"], el: ["3 rooftop μπαρ", "Θέα Ακρόπολης τη νύχτα", "Γκουρμέ δείπνο", "Κοκτέιλ"] },
    included: { en: ["Local nightlife guide", "Dinner & 2 cocktails", "Rooftop entry fees", "Hotel drop-off"], el: ["Οδηγός νυχτερινής ζωής", "Δείπνο & 2 κοκτέιλ", "Είσοδοι σε rooftop", "Αποβίβαση"] },
    meetingPoint: { en: "Monastiraki Square", el: "Πλατεία Μοναστηρακίου" },
    groupSize: "Up to 8 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "crete-elafonisi-lagoon-day-trip",
    title: { en: "Elafonisi Pink Sand Lagoon Day Trip from Chania", el: "Ημερήσια Εκδρομή στο Ελαφονήσι από τα Χανιά" },
    shortDescription: { en: "Journey to Elafonisi, famous for its pink-hued sand and turquoise shallow waters. Walk across the lagoon to the islet and relax on one of Greece's most beautiful beaches.", el: "Ταξιδέψτε στο Ελαφονήσι με τα ροζ νερά και τα τιρκουάζ ρηχά." },
    destination: "Crete",
    region: "Crete",
    type: "nature",
    typeLabel: { en: "Nature & Cultural", el: "Φύση" },
    duration: "8 hours",
    durationHours: 8,
    priceFrom: 42,
    priceLabel: { en: "from €42/person", el: "από €42/άτομο" },
    rating: 4.6,
    reviewCount: 2150,
    image: "/images/crete.webp",
    highlights: { en: ["Pink sand beach", "Turquoise lagoon", "Islet crossing", "Beach relaxation time"], el: ["Ροζ άμμος", "Τιρκουάζ λιμνοθάλασσα", "Διάσχιση στο νησάκι", "Χρόνος για μπάνιο"] },
    included: { en: ["Bus transport from Chania", "Free beach time", "English-speaking driver", "Hotel pickup"], el: ["Μεταφορά από Χανιά", "Ελεύθερος χρόνος", "Αγγλόφωνος οδηγός", "Παραλαβή"] },
    meetingPoint: { en: "Chania central bus station", el: "Κεντρικός σταθμός Χανίων" },
    groupSize: "Up to 40 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "mykonos-farm-cooking-class",
    title: { en: "Mykonos Farm Visit & Traditional Cooking Class", el: "Επίσκεψη σε Αγρόκτημα & Μάθημα Μαγειρικής" },
    shortDescription: { en: "Visit a traditional Mykonian farm, pick fresh ingredients from the garden, and learn to cook authentic Cycladic recipes with a local housewife.", el: "Επισκεφθείτε ένα παραδοσιακό αγρόκτημα και μάθετε κυκλαδίτικη μαγειρική." },
    destination: "Mykonos",
    region: "Cyclades",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία" },
    duration: "4.5 hours",
    durationHours: 4.5,
    priceFrom: 95,
    priceLabel: { en: "from €95/person", el: "από €95/άτομο" },
    rating: 4.8,
    reviewCount: 310,
    image: "/images/mykonos.webp",
    highlights: { en: ["Traditional Mykonian farm", "Garden harvest", "Cook 4 recipes", "Lunch with wine"], el: ["Παραδοσιακό αγρόκτημα", "Συγκομιδή από τον κήπο", "Μαγειρέψτε 4 συνταγές", "Γεύμα με κρασί"] },
    included: { en: ["Farm tour", "All ingredients", "Cooking instruction", "Lunch with local wine"], el: ["Περιήγηση αγροκτήματος", "Όλα τα υλικά", "Διδασκαλία μαγειρικής", "Γεύμα με κρασί"] },
    meetingPoint: { en: "Mykonos Town bus station", el: "Σταθμός λεωφορείων Μυκόνου" },
    groupSize: "Up to 8 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    badge: "local-favorite",
    featured: false
  },
  {
    slug: "kefalonia-wine-tasting-robola",
    title: { en: "Kefalonia Robola Wine Tasting & Winery Tour", el: "Γευσιγνωσία Ρομπόλας & Περιήγηση σε Οινοποιεία" },
    shortDescription: { en: "Explore Kefalonia's wine heritage by visiting two family wineries in the Robola region. Taste the famous Robola PDO wines paired with local cheeses.", el: "Δοκιμάστε τα περίφημα κρασιά Ρομπόλας σε οινοποιεία της Κεφαλονιάς." },
    destination: "Kefalonia",
    region: "Ionian Islands",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 65,
    priceLabel: { en: "from €65/person", el: "από €65/άτομο" },
    rating: 4.7,
    reviewCount: 420,
    image: "/images/kefalonia.webp",
    highlights: { en: ["2 Robola wineries", "PDO wine tasting", "Cheese pairing", "Vineyard walk"], el: ["2 οινοποιεία Ρομπόλας", "Γεύση PDO κρασιών", "Συνοδεία τυριών", "Περίπατος σε αμπελώνα"] },
    included: { en: ["Winery tours", "All tasting fees", "Local cheese platter", "Hotel transfers"], el: ["Περιηγήσεις οινοποιείων", "Όλες οι γευσιγνωσίες", "Πιατέλα τυριών", "Μεταφορές"] },
    meetingPoint: { en: "Argostoli central square", el: "Κεντρική πλατεία Αργοστολίου" },
    groupSize: "Up to 10 guests",
    difficulty: "easy",
    languages: ["en", "el", "it"],
    featured: false
  },
  {
    slug: "meteora-photography-sunset-tour",
    title: { en: "Meteora Photography Tour: Best Spots at Golden Hour", el: "Φωτογραφική Περιήγηση στα Μετέωρα" },
    shortDescription: { en: "Capture the magic of Meteora at golden hour with a professional photographer guide. Visit the most photogenic viewpoints and learn composition techniques.", el: "Απαθανατίστε τα Μετέωρα με επαγγελματία φωτογράφο." },
    destination: "Meteora",
    region: "Thessaly",
    type: "cultural",
    typeLabel: { en: "Cultural & Walking", el: "Πολιτισμός" },
    duration: "3 hours",
    durationHours: 3,
    priceFrom: 50,
    priceLabel: { en: "from €50/person", el: "από €50/άτομο" },
    rating: 4.9,
    reviewCount: 280,
    image: "/images/meteora.webp",
    highlights: { en: ["Golden hour photography", "Secret viewpoints", "Pro photographer guide", "Sunset over rock pillars"], el: ["Φωτογράφηση στο ηλιοβασίλεμα", "Μυστικά σημεία", "Επαγγελματίας φωτογράφος", "Ηλιοβασίλεμα"] },
    included: { en: ["Photographer guide", "Transport to viewpoints", "Tips & techniques", "Small group"], el: ["Φωτογράφος-οδηγός", "Μεταφορά", "Συμβουλές φωτογραφίας", "Μικρή ομάδα"] },
    meetingPoint: { en: "Kalampaka train station", el: "Σιδηροδρομικός σταθμός Καλαμπάκας" },
    groupSize: "Up to 6 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    badge: "new",
    featured: false
  },
  {
    slug: "zakynthos-turtle-island-cruise",
    title: { en: "Zakynthos Turtle Island & Marathonisi Cruise", el: "Κρουαζιέρα στο Νησί των Χελωνών & Μαραθωνήσι" },
    shortDescription: { en: "Sail to Marathonisi (Turtle Island) in the bay of Laganas. Spot the endangered Caretta-Caretta sea turtles in their natural habitat and swim in the crystal-clear shallows.", el: "Δείτε τις χελώνες Caretta-Caretta στο Μαραθωνήσι." },
    destination: "Zakynthos",
    region: "Ionian Islands",
    type: "nature",
    typeLabel: { en: "Nature & Cultural", el: "Φύση" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 35,
    priceLabel: { en: "from €35/person", el: "από €35/άτομο" },
    rating: 4.5,
    reviewCount: 1680,
    image: "/images/zakynthos.webp",
    highlights: { en: ["Turtle spotting", "Marathonisi island", "Cameo island stop", "Swim in Laganas bay"], el: ["Χελώνες Caretta-Caretta", "Μαραθωνήσι", "Νησί Cameo", "Κολύμπι"] },
    included: { en: ["Boat cruise", "Snorkeling gear", "English-speaking crew", "Hotel pickup"], el: ["Κρουαζιέρα", "Εξοπλισμός snorkeling", "Αγγλόφωνο πλήρωμα", "Παραλαβή"] },
    meetingPoint: { en: "Laganas port or hotel pickup", el: "Λιμάνι Λαγανά" },
    groupSize: "Up to 25 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "rhodes-valley-butterflies-lindos",
    title: { en: "Valley of the Butterflies & Lindos Village Day Trip", el: "Πεταλούδες & Λίνδος Ημερήσια Εκδρομή" },
    shortDescription: { en: "Walk through the lush Valley of the Butterflies (Petaloudes), then continue to Lindos for free time exploring the whitewashed streets and shops.", el: "Περπατήστε στην Κοιλάδα των Πεταλούδων και συνεχίστε στη Λίνδο." },
    destination: "Rhodes",
    region: "Dodecanese",
    type: "nature",
    typeLabel: { en: "Nature & Cultural", el: "Φύση" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 45,
    priceLabel: { en: "from €45/person", el: "από €45/άτομο" },
    rating: 4.4,
    reviewCount: 1310,
    image: "/images/rhodes.webp",
    highlights: { en: ["Valley of the Butterflies", "Wooden boardwalk trail", "Lindos free time", "Coastal drive"], el: ["Κοιλάδα Πεταλούδων", "Ξύλινη διαδρομή", "Ελεύθερος χρόνος Λίνδος", "Παράκτια διαδρομή"] },
    included: { en: ["Bus transport", "Entrance fee", "English-speaking driver", "Free time in Lindos"], el: ["Μεταφορά", "Εισιτήριο", "Αγγλόφωνος οδηγός", "Ελεύθερος χρόνος"] },
    meetingPoint: { en: "Rhodes Town, Eleftherias Square", el: "Πλατεία Ελευθερίας, Ρόδος" },
    groupSize: "Up to 20 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "corfu-canal-damour-north-coast-tour",
    title: { en: "Corfu North Coast: Canal d'Amour, Sidari & Paleokastritsa", el: "Βόρεια Κέρκυρα: Canal d'Amour, Σιδάρι & Παλαιοκαστρίτσα" },
    shortDescription: { en: "Explore Corfu's dramatic northern coastline with its famous Canal d'Amour rock formations, the resort town of Sidari, and the stunning Paleokastritsa Monastery.", el: "Εξερευνήστε τη βόρεια ακτή της Κέρκυρας και το Canal d'Amour." },
    destination: "Corfu",
    region: "Ionian Islands",
    type: "nature",
    typeLabel: { en: "Nature & Cultural", el: "Φύση" },
    duration: "6 hours",
    durationHours: 6,
    priceFrom: 48,
    priceLabel: { en: "from €48/person", el: "από €48/άτομο" },
    rating: 4.5,
    reviewCount: 920,
    image: "/images/corfu.webp",
    highlights: { en: ["Canal d'Amour", "Sidari resort", "Paleokastritsa Monastery", "Coastal viewpoints"], el: ["Canal d'Amour", "Σιδάρι", "Μονή Παλαιοκαστρίτσας", "Παράκτια θέα"] },
    included: { en: ["Bus transport", "English-speaking guide", "Free swimming time", "Hotel pickup"], el: ["Μεταφορά", "Αγγλόφωνος ξεναγός", "Ελεύθερος χρόνος", "Παραλαβή"] },
    meetingPoint: { en: "Corfu Town, Liston Arcade", el: "Λιστόν, Κέρκυρα" },
    groupSize: "Up to 20 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "thessaloniki-olympian-riviera-day-trip",
    title: { en: "Thessaloniki to Olympian Riviera & Dion Archaeological Park", el: "Εκδρομή στην Ολυμπιακή Ριβιέρα & το Δίον" },
    shortDescription: { en: "Travel south to the beautiful Olympian Riviera, visit the ancient city of Dion at the foot of Mount Olympus, and enjoy a seaside lunch in Litochoro.", el: "Ταξιδέψτε στην Ολυμπιακή Ριβιέρα και επισκεφθείτε το αρχαίο Δίον." },
    destination: "Thessaloniki",
    region: "Macedonia",
    type: "history",
    typeLabel: { en: "History & Archaeology", el: "Ιστορία" },
    duration: "8 hours",
    durationHours: 8,
    priceFrom: 62,
    priceLabel: { en: "from €62/person", el: "από €62/άτομο" },
    rating: 4.6,
    reviewCount: 340,
    image: "/images/thessaloniki.webp",
    highlights: { en: ["Dion Archaeological Site", "Mount Olympus views", "Litochoro seaside town", "Olympian Riviera drive"], el: ["Αρχαίο Δίον", "Θέα Ολύμπου", "Λιτόχωρο", "Ολυμπιακή Ριβιέρα"] },
    included: { en: ["Air-conditioned transport", "Dion entrance fee", "English-speaking guide", "Seaside lunch"], el: ["Μεταφορά", "Εισιτήριο Δίου", "Αγγλόφωνος ξεναγός", "Γεύμα"] },
    meetingPoint: { en: "Thessaloniki, Aristotelous Square", el: "Πλατεία Αριστοτέλους, Θεσσαλονίκη" },
    groupSize: "Up to 15 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "halkidiki-sithonia-safari-tour",
    title: { en: "Halkidiki Sithonia Peninsula Safari: Beaches & Villages", el: "Σαφάρι στη Σιθωνία: Παραλίες & Χωριά" },
    shortDescription: { en: "Explore the rugged Sithonia peninsula by 4x4 vehicle. Visit secluded beaches like Kavourotrypes, traditional fishing villages, and enjoy a fish taverna lunch.", el: "Εξερευνήστε τη Σιθωνία με 4x4, σε απόμερες παραλίες και ψαροχώρια." },
    destination: "Halkidiki",
    region: "Macedonia",
    type: "adventure",
    typeLabel: { en: "Adventure & Hiking", el: "Περιπέτεια" },
    duration: "7 hours",
    durationHours: 7,
    priceFrom: 65,
    priceLabel: { en: "from €65/person", el: "από €65/άτομο" },
    rating: 4.7,
    reviewCount: 580,
    image: "/images/halkidiki.webp",
    highlights: { en: ["4x4 off-road adventure", "Kavourotrypes beaches", "Traditional villages", "Fish taverna lunch"], el: ["4x4 περιπέτεια", "Παραλίες Καβουρότρυπες", "Παραδοσιακά χωριά", "Γεύμα με ψάρι"] },
    included: { en: ["4x4 vehicle & driver", "Local guide", "Lunch at seaside taverna", "Hotel pickup/drop-off"], el: ["Όχημα 4x4", "Τοπικός οδηγός", "Γεύμα σε ταβέρνα", "Παραλαβή"] },
    meetingPoint: { en: "Neos Marmaras central square", el: "Κεντρική πλατεία Νέου Μαρμαρά" },
    groupSize: "Up to 8 guests",
    difficulty: "moderate",
    languages: ["en", "el", "ru"],
    featured: false
  },
  {
    slug: "paros-wine-tasting-island-tour",
    title: { en: "Paros Wine & Produce Tasting: Moraitis Winery & Local Farms", el: "Οινογνωσία & Τοπικά Προϊόντα στην Πάρο" },
    shortDescription: { en: "Visit the historic Moraitis Winery in Naoussa, taste Parian wines and local delicacies, and explore a traditional cheese farm producing the famous xinomizithra.", el: "Επισκεφθείτε το οινοποιείο Μωραΐτη και δοκιμάστε παριανά κρασιά." },
    destination: "Paros",
    region: "Cyclades",
    type: "food",
    typeLabel: { en: "Gastronomy & Wine", el: "Γαστρονομία" },
    duration: "4 hours",
    durationHours: 4,
    priceFrom: 58,
    priceLabel: { en: "from €58/person", el: "από €58/άτομο" },
    rating: 4.7,
    reviewCount: 290,
    image: "/images/paros.webp",
    highlights: { en: ["Moraitis Winery tour", "8-wine tasting", "Cheese farm visit", "Local appetizers"], el: ["Οινοποιείο Μωραΐτη", "Γευσιγνωσία 8 κρασιών", "Επίσκεψη τυροκομείου", "Τοπικοί μεζέδες"] },
    included: { en: ["Winery tour & tasting", "Cheese farm visit", "Local guide", "Transport from Parikia"], el: ["Επίσκεψη & γευσιγνωσία", "Επίσκεψη τυροκομείου", "Τοπικός οδηγός", "Μεταφορά"] },
    meetingPoint: { en: "Parikia central bus station", el: "Κεντρικός σταθμός λεωφορείων Παροικιάς" },
    groupSize: "Up to 10 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    featured: false
  },
  {
    slug: "milos-sarakiniko-lunar-landscape-tour",
    title: { en: "Milos: Sarakiniko, Catacombs & Plaka Castle Sunset Walk", el: "Μήλος: Σαρακίνικο, Κατακόμβες & Πλάκα" },
    shortDescription: { en: "Explore Milos' unique lunar landscape at Sarakiniko, visit the early Christian catacombs, and end the day watching the sunset from Plaka Castle.", el: "Εξερευνήστε το φεγγαρότοπο του Σαρακίνικου και το ηλιοβασίλεμα στην Πλάκα." },
    destination: "Milos",
    region: "Cyclades",
    type: "cultural",
    typeLabel: { en: "Cultural & Walking", el: "Πολιτισμός" },
    duration: "5 hours",
    durationHours: 5,
    priceFrom: 40,
    priceLabel: { en: "from €40/person", el: "από €40/άτομο" },
    rating: 4.7,
    reviewCount: 860,
    image: "/images/milos.webp",
    highlights: { en: ["Sarakiniko white rocks", "Early Christian catacombs", "Plaka Castle sunset", "Milos mining museum"], el: ["Σαρακίνικο", "Παλαιοχριστιανικές κατακόμβες", "Ηλιοβασίλεμα Πλάκας", "Μουσείο Μεταλλείων"] },
    included: { en: ["Local guide", "Entrance to catacombs", "Transport between sites", "Bottled water"], el: ["Τοπικός ξεναγός", "Είσοδος κατακομβών", "Μεταφορά", "Νερό"] },
    meetingPoint: { en: "Plaka village square, Milos", el: "Πλατεία Πλάκας, Μήλος" },
    groupSize: "Up to 12 guests",
    difficulty: "easy",
    languages: ["en", "el"],
    badge: "local-favorite",
    featured: false
  }
];
